using CWB.App.Models.BusinessProcesses;
using CWB.App.Models.WorkOrder;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CWB.App.Services.ProductionPlanWo
{
    public interface IWOService
    {
        Task<IEnumerable<WOSOVM>> GetSoWoRel(long workOrderId);
        Task<List<ProductionPlan_WoVM>> ProductionPlanWoPost(IEnumerable<ProductionPlan_WoVM> productions);
        Task<List<Input_Resrv_ListVM>> PostInputReservelist(IEnumerable<Input_Resrv_ListVM> allocations);
        Task<List<ProductionPlan_WoVM>> ProductionPlanWoPostFreeze(IEnumerable<ProductionPlan_WoVM> productions);
        Task<List<ProductionPlan_WoVM>> ProductionPlanWoPostConsolidation(IEnumerable<ProductionPlan_WoVM> productions);
        Task<List<ProductionPlan_WoVM>> UpdateProduction_WoForReference(IEnumerable<ProductionPlan_WoVM> productions);
        Task<List<ConsolidatedWoMappingVM>> PostConsolidatedWO(IEnumerable<ConsolidatedWoMappingVM> productions);
        Task<IEnumerable<ConsolidatedWoMappingVM>> Getallconsolidationproductionwo();
        Task<ProductionPlan_WoVM> UpdateProductionPlan_Wo(ProductionPlan_WoVM productions);
        Task<ProductionPlan_WoVM> UpdateHoldProductionPlan_Wo(ProductionPlan_WoVM productions);
        Task<ProductionPlan_WoVM> UpdateProductionPlan_WoCritcalPart(ProductionPlan_WoVM productions);
        Task<ProductionPlan_WoVM> UpdateProductionPlanTestData(ProductionPlan_WoVM productions);
        Task<ProductionPlan_WoVM> UpdateProductionPlan_WoAllocatedqntyandstatus(ProductionPlan_WoVM productions);
        Task<IEnumerable<ProductionPlan_WoVM>> AllProductionPlan_Wo();
        Task<IEnumerable<ProductionPlan_WoVM>> AllProductionWoReadForProd();

        Task<List<Input_Resrv_ListVM>> GetallInputreservelistbypartid(long partId);
        Task<List<Input_Resrv_ListVM>> GetallInputreservelist();
        Task<IEnumerable<ProductionPlan_WoVM>> GetAllReadyforProductionWo();
        Task<List<ProcPlanVM>> ProcPlanPost(IEnumerable<ProcPlanVM> procPlans);
        Task<List<ProcPlanVM>> ProcPlanPostPOFlag(IEnumerable<ProcPlanVM> procPlans);
        Task<List<WorkOrdersVM>> UpdateMultipleWorkOrder(IEnumerable<WorkOrdersVM> workOrders);
        Task<List<BOMListVM>> BomListPost(IEnumerable<BOMListVM> bomlist);
        Task<List<ProcPlanPartPurChaseRelVM>> ProcPurchasePost(IEnumerable<ProcPlanPartPurChaseRelVM> bomlist);
        Task<IEnumerable<ProcPlanVM>> GetAllProcPlan();
        Task<IEnumerable<BOMListVM>> GetAllBomlist();
        Task<IEnumerable<WoSubConSupplierVM>> GetAllSubCOnSupp();
        Task<IEnumerable<PODetailsVM>> GetAllPodetails();
        Task<WOStatusVM> GetWOStatus(long Id);
        Task<Inv_Trans_ListVM> GetInv_trans_Desc(long Id);
        Task<List<ChildWoRelVM>> PostChildWoRel(IEnumerable<ChildWoRelVM> childWoRels);
        Task<List<McTimeListVM>> PostMcTimeList(IEnumerable<McTimeListVM> mcTimeListVMs);
        Task<IEnumerable<McTimeListVM>> GetAllMcTimeList();
        Task<IEnumerable<WorkOrdersVM>> AllParentChildWos(long parentWoId);
        Task<WoSubConSupplierVM> PostSubConSupplier(WoSubConSupplierVM childWoRels);

        Task<bool> DeleteSubCon(long doctypeId);
        Task<bool> DeleteWo(long doctypeId);
        Task<bool> DeleteWoSoRel(long doctypeId);
        Task<bool> Deleteproductionplansplitwo(long doctypeId);
        Task<bool> Deleteforreryalloc(long doctypeId);
        Task<List<PODetailsVM>> PODetails(IEnumerable<PODetailsVM> pODetails);
        Task<List<PODetailsVM>> UpdateInspection(IEnumerable<PODetailsVM> pODetails);
        Task<List<POHeaderVM>> POHeader(IEnumerable<POHeaderVM> pOHeaderVMs);
        Task<Inw_Recpt_HeaderVM> PostInw_Recpt_Header(Inw_Recpt_HeaderVM childWoRels);
        Task<SetupVariationReasonVM> PostSetupVariationReason(SetupVariationReasonVM childWoRels);
        Task<Inw_Recpt_DetailsVM> PostInw_Recpt_Details(Inw_Recpt_DetailsVM childWoRels);
        Task<Insp_Outcome_DetailsVM> PostNcLog(Insp_Outcome_DetailsVM childWoRels);

        Task<IEnumerable<InwardDocTypeVM>> GetAllInWardDocList();
        Task<Inw_Recpt_Part_NoVM> PostInw_Recpt_Part_No(Inw_Recpt_Part_NoVM inwardDocTypeVM);
        Task<InwardDocTypeVM> PostInWardDocList(InwardDocTypeVM inwardDocTypeVM);
        Task<bool> DeleteInWardDocList(long itemMasterDocListId);
        Task<IEnumerable<InspectDocTypeVM>> GetAllInspectDocList();
        Task<InspectDocTypeVM> PostInspectDocList(InspectDocTypeVM InspectDocTypeVM);
        Task<bool> DeleteInspectDocList(long itemMasterDocListId);
        Task<IEnumerable<LineInspectDocTypeVM>> GetAllLineDocList();
        Task<LineInspectDocTypeVM> PostLineDocList(LineInspectDocTypeVM LineDocTypeVM);
        Task<bool> DeleteLineDocList(long itemMasterDocListId);
        Task<IEnumerable<FinalInspectDocTypeVM>> GetAllFinalDocList();
        Task<FinalInspectDocTypeVM> PostFinalDocList(FinalInspectDocTypeVM FinalDocTypeVM);
        Task<bool> DeleteFinalDocList(long itemMasterDocListId);
        Task<IEnumerable<Cust_NC_Decs_MatrixVM>> GetAllCust_NC_Decs_Matrix();
        Task<Cust_NC_Decs_MatrixVM> PostCust_NC_Decs_Matrix(Cust_NC_Decs_MatrixVM FinalDocTypeVM);
        Task<bool> DeleteCust_NC_Decs_Matrix(long itemMasterDocListId);
        Task<IEnumerable<Cust_NC_Decs_Matrix_OptVM>> GetAllCust_NC_Decs_Matrix_Opt();
        Task<Cust_NC_Decs_Matrix_OptVM> PostCust_NC_Decs_Matrix_Opt(Cust_NC_Decs_Matrix_OptVM FinalDocTypeVM);
        Task<bool> DeleteCust_NC_Decs_Matrix_Opt(long itemMasterDocListId);
        Task<bool> DeleteNC_Wk_List_Tmpl_Head(long itemMasterDocListId);
        Task<bool> DeleteNC_Wk_List_Tmpl_Det(long itemMasterDocListId);
        Task<IEnumerable<RcCaDocTypeVM>> GetAllRcaCaDocList();
        Task<IEnumerable<OperationSettingsVM>> GetAllOperationSettings();
        Task<IEnumerable<NC_Wk_List_Tmpl_DetVM>> GetAllNC_Wk_List_Tmpl_Det();
        Task<IEnumerable<NC_Wk_List_Tmpl_HeadVM>> GetAllNC_Wk_List_Tmpl_Head();
        Task<IEnumerable<Cont_RCA_CA_LogVM>> GetAllCont_RCA_CA_log();
        Task<IEnumerable<Inv_Mismatch_ListVM>> GetAllInv_Mismatch_List();
        Task<IEnumerable<Inv_Master_LogVM>> GetAllInv_Master_Log();
        Task<IEnumerable<Inv_Trans_LogVM>> GetAllInv_Trans_Log();
        Task<IEnumerable<Inventory_MasterVM>> GetAllInventory_Master();
        Task<IEnumerable<Inventory_MasterVM>> GetAllInventory_MasterBypartid(long locationId, long oprnoId, long routingId, long partid);
        Task<IEnumerable<Inventory_MasterVM>> GetAllInventory_MasterBypartidWithFlag(string flag, long locationId, long oprnoId, long routingId, long partid);
        Task<IEnumerable<NC_Decision_LogVM>> GetAllNC_Decision_Log();
        Task<IEnumerable<NC_Disp_Decision_ListVM>> GetAllNC_Disp_Decision_List();
        Task<IEnumerable<NC_Disp_Decs_Appl_ListVM>> GetAllNC_Disp_Decs_Appl_List();
        Task<IEnumerable<Inw_Recpt_HeaderVM>> GetAllInw_Recpt_Header();
        Task<IEnumerable<Inward_Condn_listVM>> GetAllInward_Condn_list();
        Task<IEnumerable<SetupVariationReasonVM>> GetAllSetupVariationReason();
        Task<IEnumerable<Cust_NC_DecisionVM>> GetAllCust_NC_Decision();
        Task<IEnumerable<Inw_Recpt_DetailsVM>> GetAllInw_Recpt_Details();
        Task<IEnumerable<Insp_Outcome_DetailsVM>> GetAllNcLog();
        Task<RcCaDocTypeVM> PostRcaCaDocList(RcCaDocTypeVM RcaCaDocTypeVM);
        Task<NC_Wk_List_Tmpl_DetVM> PostNC_Wk_List_Tmpl_Det(NC_Wk_List_Tmpl_DetVM RcaCaDocTypeVM);
        Task<NC_Disp_Decs_Appl_ListVM> PostNC_Disp_Decs_Appl_List(NC_Disp_Decs_Appl_ListVM RcaCaDocTypeVM);
        Task<NC_Wk_List_Tmpl_HeadVM> PostNC_Wk_List_Tmpl_Head(NC_Wk_List_Tmpl_HeadVM RcaCaDocTypeVM);
        Task<Cont_RCA_CA_LogVM> PostCont_RCA_CA_Log(Cont_RCA_CA_LogVM RcaCaDocTypeVM);
        Task<Inv_Master_LogVM> PostInv_Master_Log(Inv_Master_LogVM RcaCaDocTypeVM);
        Task<Inv_Mismatch_ListVM> PostInv_Mismatch_List(Inv_Mismatch_ListVM RcaCaDocTypeVM);
        Task<Inventory_MasterVM> PostInventory_Master(Inventory_MasterVM RcaCaDocTypeVM);
        Task<Inv_Trans_LogVM> PostInv_Trans_Log(Inv_Trans_LogVM RcaCaDocTypeVM);
        Task<NC_Decision_LogVM> PostNC_Decision_Log(NC_Decision_LogVM RcaCaDocTypeVM);
        Task<OperationSettingsVM> PostOperationsSettings(OperationSettingsVM RcaCaDocTypeVM);
        Task<bool> DeleteRcaCaDocList(long itemMasterDocListId);
        Task<bool> DeleteInvMismatch(long itemMasterDocListId);
        Task<bool> DeleteNC_Disp_Decs_Appl_List(long itemMasterDocListId);


        Task<IEnumerable<WO_Wait_ListVM>> GetAllWO_Wait_List();
        Task<WO_Wait_ListVM> PostWO_Wait_List(WO_Wait_ListVM FinalDocTypeVM);
        Task<bool> DeleteWO_Wait_List(long itemMasterDocListId);
        Task<bool> DeleteInv_Mismatch_List(long itemMasterDocListId);
        Task<bool> DeleteInv_Master_Log(long itemMasterDocListId);
        Task<IEnumerable<TempWO_Wait_ListVM>> GetAllTempWo_Wait_List();
        Task<TempWO_Wait_ListVM> PostTempWo_Wait_List(TempWO_Wait_ListVM FinalDocTypeVM);
        Task<bool> DeleteTempWo_Wait_List(long itemMasterDocListId);
        Task<IEnumerable<Mc_Not_Avl_ReasonVM>> GetAllMc_not_avl_reason();
        Task<Mc_Not_Avl_ReasonVM> PostMc_not_avl_reason(Mc_Not_Avl_ReasonVM FinalDocTypeVM);
        Task<IEnumerable<Timeslot_SettingVM>> GetAllTimeslot_Setting();
        Task<Timeslot_SettingVM> PostTimeslot_Setting(Timeslot_SettingVM FinalDocTypeVM);
        Task<bool> DeleteTimeslot_Setting(long itemMasterDocListId);
        Task<IEnumerable<Timeslot_ListVM>> GetAllTimeslot_List();
        Task<Timeslot_ListVM> PostTimeslot_List(Timeslot_ListVM FinalDocTypeVM);
        Task<bool> DeleteTimeslot_List(long itemMasterDocListId);
        Task<IEnumerable<Mc_Timeslot_ListVM>> GetAllMc_Timeslot_List();
        Task<Mc_Timeslot_ListVM> PostMc_Timeslot_List(Mc_Timeslot_ListVM FinalDocTypeVM);
        Task<bool> DeleteMc_Timeslot_List(long itemMasterDocListId);
        Task<IEnumerable<TempMc_Timeslot_ListVM>> GetAllTempMc_Timeslot_List();
        Task<TempMc_Timeslot_ListVM> PostTempMc_Timeslot_List(TempMc_Timeslot_ListVM FinalDocTypeVM);
        Task<bool> DeleteTempMc_Timeslot_List(long itemMasterDocListId);
        Task<IEnumerable<Mc_Wait_ListVM>> GetAllMc_Wait_List();
        Task<IEnumerable<TempMc_Wait_ListVM>> GetAllSetUpApprolList();
        Task<IEnumerable<TempMc_Wait_ListVM>> GetAllSetUpCnfList();
        Task<IEnumerable<TempMc_Wait_ListVM>> GetAllBookOutList();
        Task<Mc_Wait_ListVM> PostMc_Wait_List(Mc_Wait_ListVM FinalDocTypeVM);
        Task<bool> DeleteMc_Wait_List(long itemMasterDocListId);
        Task<IEnumerable<Matl_Issue_SettingsVM>> GetAllMatl_Issue_Settings();
        Task<Matl_Issue_SettingsVM> PostMatl_Issue_Settings(Matl_Issue_SettingsVM FinalDocTypeVM);
        Task<bool> DeleteMatl_Issue_Settings(long itemMasterDocListId);
        Task<IEnumerable<DispatchQntyVM>> GetAllDispatchQnty();
        Task<DispatchQntyVM> PostDispatchQnty(DispatchQntyVM FinalDocTypeVM);
        Task<bool> DeleteDispatchQnty(long itemMasterDocListId);
        Task<IEnumerable<DispatchDetailsVM>> GetAllDispatchDetails();
        Task<DispatchDetailsVM> PostDispatchDetails(DispatchDetailsVM FinalDocTypeVM);
        Task<bool> DeleteDispatchDetails(long itemMasterDocListId);
        Task<IEnumerable<Matl_Issue_ListVM>> GetAllMatl_Issue_List();
        Task<IEnumerable<Matl_Issue_ListVM>> GetAllMatlIssueListForShop();
        Task<Matl_Issue_ListVM> PostMatl_Issue_List(Matl_Issue_ListVM FinalDocTypeVM);
        Task<bool> DeleteMatl_Issue_List(long itemMasterDocListId);
        Task<IEnumerable<TempMc_Wait_ListVM>> GetAllTempMc_Wait_List();
        Task<TempMc_Wait_ListVM> PostTempMc_Wait_List(TempMc_Wait_ListVM FinalDocTypeVM);
        Task<bool> DeleteTempMc_Wait_List(long itemMasterDocListId);
        Task<IEnumerable<Non_Plan_Wk_ListVM>> GetAllNon_Plan_Wk_List();
        Task<IEnumerable<Non_Plan_Wk_type_ListVM>> GetAllNon_Plan_Wk_type_List();
        Task<IEnumerable<Mode_ListVM>> GetAllMode_List();
        Task<Non_Plan_Wk_ListVM> PostNon_Plan_Wk_List(Non_Plan_Wk_ListVM FinalDocTypeVM);
        Task<bool> DeleteNon_Plan_Wk_List(long itemMasterDocListId);
        Task<IEnumerable<Rwk_ListVM>> GetAllRwk_List();
        Task<Rwk_ListVM> PostRwk_List(Rwk_ListVM FinalDocTypeVM);
        Task<bool> DeleteRwk_List(long itemMasterDocListId);
        Task<IEnumerable<Shop_Insp_LogVM>> GetAllShop_Insp_Log();
        Task<Shop_Insp_LogVM> PostShop_Insp_Log(Shop_Insp_LogVM FinalDocTypeVM);
        Task<bool> DeleteShop_Insp_Log(long itemMasterDocListId);
        Task<IEnumerable<SubCon_ListVM>> GetAllSubCon_List();
        Task<SubCon_ListVM> PostSubCon_List(SubCon_ListVM FinalDocTypeVM);
        Task<bool> DeleteSubCon_List(long itemMasterDocListId);
        Task<IEnumerable<TempSubCon_ListVM>> GetAllTempSubCon_List();
        Task<TempSubCon_ListVM> PostTempSubCon_List(TempSubCon_ListVM FinalDocTypeVM);
        Task<bool> DeleteTempSubCon_List(long itemMasterDocListId);
        Task<IEnumerable<Opr_ListVM>> GetAllOpr_List();
        Task<IEnumerable<Mc_Wait_ListVM>> GetAllMc_Wait_ListByMcWait(long woid);
        Task<Opr_ListVM> PostOpr_List(Opr_ListVM FinalDocTypeVM);
        Task<bool> DeleteOpr_List(long itemMasterDocListId);
        Task<IEnumerable<TempOpr_ListVM>> GetAllTempOpr_List();
        Task<IEnumerable<TempOpr_ListVM>> GetAllTempOpr_Listwithroutingidandwoid(long routingId, long woId);
        Task<TempOpr_ListVM> PostTempOpr_List(TempOpr_ListVM FinalDocTypeVM);
        Task<bool> DeleteTempOpr_List(long itemMasterDocListId);
        Task<IEnumerable<ProcPlanPartPurChaseRelVM>> ProcPlanPartPurChaseRel(long procPlanId);

    }
}
