using CWB.ProductionPlanWO.Domain;
using CWB.ProductionPlanWO.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CWB.ProductionPlanWO.Services
{
    public interface IWOService
    {
        Task<WorkOrdersVM> WorkOrder(WorkOrdersVM workOrdersVM);
        Task<WoSubConSupplierVM> PostWoSubCon(WoSubConSupplierVM workOrdersVM);
        Task<IEnumerable<WorkOrdersVM>> AllWorkOrders(long tenantId);
        Task<IEnumerable<POLogVM>> GetWoPOLogs(long tenantId, long customerOrderId);
        Task<IEnumerable<POLogVM>> GetPOLogs(long tenantId, long poid);
        Task<IEnumerable<WoSubConSupplierVM>> GetAllWoSubCon(long tenantId);
        Task<IEnumerable<WorkOrdersVM>> AllParentChildWo(long ParentWoId, long tenantId);
        Task<IEnumerable<WOSOVM>> GetSoWo(long workOrderId);
        Task<IEnumerable<ProcPlanPartPurChaseRelVM>> GetProcPurchase(long procPlanId);
        Task<List<ProcPlanPartPurChaseRelVM>> PostProcPurchase(List<ProcPlanPartPurChaseRelVM> woso);
        Task<WorkOrdersVM> GetSingleWO(long Id, long tenantId);
        Task<List<WorkOrdersVM>> MultipleWorkOrder(List<WorkOrdersVM> workOrdersVM);
        Task<List<WorkOrdersVM>> UpdateMultipleWorkOrder(List<WorkOrdersVM> workOrdersVM);
        Task<List<WOSOVM>> PostWOSO(List<WOSOVM> woso);
        Task<List<ProcPlanVM>> PostProcPlan(List<ProcPlanVM> proc);
        Task<List<BOMListVM>> PostBomList(List<BOMListVM> bomlist);
        Task<List<BOMTempVM>> BOMTempPost(List<BOMTempVM> bomVm);
        Task<IEnumerable<ProcPlanVM>> AllProcPlan(long tenantId);
        Task<IEnumerable<BOMListVM>> AllBomList(long tenantId);
        Task<List<ProductionPlan_WOVM>> PostProductionPlan_Wo(List<ProductionPlan_WOVM> productions);
        Task<IEnumerable<ProductionPlan_WOVM>> AllProductionWo(long tenantId);
        Task<WOStatusVM> GetWOStatus(long Id);
        Task<bool> DeleteSubCon(long Id);
        Task<bool> DeleteWo(long Id);
        Task<List<ChildWoRelVM>> PostChildWoRel(List<ChildWoRelVM> childWos);
        Task<List<McTimeListVM>> PostMcTimeList(List<McTimeListVM> mcTimeLists);
        Task<IEnumerable<McTimeListVM>> GetAllMcTimeListVMs(long tenantId);
        Task<IEnumerable<PODetailsVM>> GetAllPodetails(long tenantId);
        Task<POStatusVM> GetPOStatus(long Id);
        Task<List<PODetailsVM>> MultiplePODetails(List<PODetailsVM> pODetailsVM);
        Task<List<POHeaderVM>> MultiplePOHeaders(List<POHeaderVM> pOHeaderVMs);
        Task<IEnumerable<Inward_Condn_listVM>> GetAllInward_Condn_list();
        Task<IEnumerable<Insp_Outcome_DetailsVM>> GetAllInsp_Outcome_Details(long tenantId);
        Task<IEnumerable<Insp_Outcome_ListVM>> GetAllInsp_Outcome_List();
        Task<IEnumerable<Inventory_MasterVM>> GetAllInventory_Master(long tenantId);
        Task<IEnumerable<Inv_Trans_LogVM>> GetAllInvTransLog(long tenantId);
        Task<IEnumerable<Inw_Recpt_DetailsVM>> GetAllInw_Recpt_Details(long tenantId);
        Task<IEnumerable<Inw_Recpt_HeaderVM>> GetAlInw_Recpt_Header(long tenantId);
        Task<IEnumerable<Inw_Recpt_Part_NoVM>> GetAlInw_Recpt_Part_No(long tenantId);
        Task<Insp_Outcome_DetailsVM> PostInsp_Outcome_Details(Insp_Outcome_DetailsVM workOrdersVM);
        Task<Insp_Outcome_ListVM> PostInsp_Outcome_List(Insp_Outcome_ListVM workOrdersVM);
        Task<Inventory_MasterVM> PostInventory_Master(Inventory_MasterVM workOrdersVM);
        Task<Inv_Trans_LogVM> PostInv_Trans_Log(Inv_Trans_LogVM workOrdersVM);
        Task<Inw_Recpt_DetailsVM> PostInw_Recpt_Details(Inw_Recpt_DetailsVM workOrdersVM);
        Task<Inw_Recpt_HeaderVM> PostInw_Recpt_Header(Inw_Recpt_HeaderVM workOrdersVM);
        Task<Inw_Recpt_Part_NoVM> PostInw_Recpt_Part_No(Inw_Recpt_Part_NoVM workOrdersVM);
        Task<Inward_Condn_listVM> PostInward_Condn_list(Inward_Condn_listVM workOrdersVM);
        Task<bool> DeleteInsp_OutcomeDetails(long Id);
        Task<bool> DeleteInventory_Master(long Id);
        Task<bool> DeleteInv_Trans_Log(long Id);
        Task<bool> DeleteInw_Recpt_Details(long Id);
        Task<bool> DeleteInw_Recpt_Header(long Id);
        Task<bool> DeleteInw_Recpt_Part_No(long Id);
        Task<IEnumerable<InwardDocTypeVM>> GetAllInwardDocList(long tenantId);
        Task<InwardDocTypeVM> PostInwardDocList(InwardDocTypeVM itemMasterDocList);
        Task<bool> DeleteInwardDoc(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<LineInspectDocTypeVM>> GetAllLineInspectDocList(long tenantId);
        Task<LineInspectDocTypeVM> PostLineInspectDocList(LineInspectDocTypeVM itemMasterDocList);
        Task<bool> DeleteLineInspectDoc(long itemMasterDocListId, long tenantId);
        Task<bool> DeleteCont_RCA_CA_Log(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<FinalInspectDocTypeVM>> GetAllFinalInspectDocList(long tenantId);
        Task<FinalInspectDocTypeVM> PostFinalInspectDocList(FinalInspectDocTypeVM itemMasterDocList);
        Task<OperationSettingsVM> PostOperationSettings(OperationSettingsVM itemMasterDocList);
        Task<Cont_RCA_CA_LogVM> PostCont_RCA_CA_Log(Cont_RCA_CA_LogVM itemMasterDocList);
        Task<bool> DeleteFinalInspectDoc(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<InspectDocTypeVM>> GetAllInspectDocList(long tenantId);
        Task<InspectDocTypeVM> PostInspectDocList(InspectDocTypeVM itemMasterDocList);
        Task<bool> DeleteInspectDoc(long itemMasterDocListId, long tenantId);

        Task<IEnumerable<RcCaDocTypeVM>> GetAllRcCaDocList(long tenantId);
        Task<RcCaDocTypeVM> PostRcCaDocList(RcCaDocTypeVM itemMasterDocList);
        Task<bool> DeleteRcCaDoc(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<NcLogStatusVM>> GetAllNcLogStatusList();
        Task<IEnumerable<OperationSettingsVM>> GetAllOperationSettings();
        Task<IEnumerable<Cont_RCA_CA_LogVM>> GetAllCont_RCA_CA_Log(long tenantId);
        Task<NcLogStatusVM> PostNcLogStatusList(NcLogStatusVM itemMasterDocList);
        Task<bool> DeleteNcLogStatus(long itemMasterDocListId);

        Task<IEnumerable<NC_Decision_LogVM>> GetAllNC_Decision_Log(long tenantId);
        Task<NC_Decision_LogVM> PostNC_Decision_Log(NC_Decision_LogVM itemMasterDocList);
        Task<bool> DeleteNC_Decision_Log(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<NC_Wk_List_Tmpl_DetVM>> GetAllNC_Wk_List_Tmpl_Det(long tenantId);
        Task<NC_Wk_List_Tmpl_DetVM> PostNC_Wk_List_Tmpl_Det(NC_Wk_List_Tmpl_DetVM itemMasterDocList);
        Task<bool> DeleteNC_Wk_List_Tmpl_Det(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<NC_Disp_Decs_Appl_ListVM>> GetAllNC_Disp_Decs_Appl_List(long tenantId);
        Task<NC_Disp_Decs_Appl_ListVM> PostNC_Disp_Decs_Appl_List(NC_Disp_Decs_Appl_ListVM itemMasterDocList);
        Task<bool> DeleteNC_Disp_Decs_Appl_List(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<NC_Wk_List_Tmpl_HeadVM>> GetAllNC_Wk_List_Tmpl_Head(long tenantId);
        Task<NC_Wk_List_Tmpl_HeadVM> PostNC_Wk_List_Tmpl_Head(NC_Wk_List_Tmpl_HeadVM itemMasterDocList);
        Task<bool> DeleteNC_Wk_List_Tmpl_Head(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<NC_Work_ListVM>> GetAllNC_Work_List(long tenantId);
        Task<NC_Work_ListVM> PostNC_Work_List(NC_Work_ListVM itemMasterDocList);
        Task<bool> DeleteNC_Work_List(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<NC_Wk_List_HeaderVM>> GetAllNC_Wk_List_Header(long tenantId);
        Task<NC_Wk_List_HeaderVM> PostNC_Wk_List_Header(NC_Wk_List_HeaderVM itemMasterDocList);
        Task<bool> DeleteNC_Wk_List_Header(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<Cust_NC_Decs_Matrix_OptVM>> GetAllCust_NC_Decs_Matrix_Opt(long tenantId);
        Task<Cust_NC_Decs_Matrix_OptVM> PostCust_NC_Decs_Matrix_Opt(Cust_NC_Decs_Matrix_OptVM itemMasterDocList);
        Task<bool> DeleteCust_NC_Decs_Matrix_Opt(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<Cust_NC_Decs_MatrixVM>> GetAllCust_NC_Decs_Matrix(long tenantId);
        Task<Cust_NC_Decs_MatrixVM> PostCust_NC_Decs_Matrix(Cust_NC_Decs_MatrixVM itemMasterDocList);
        Task<bool> DeleteCust_NC_Decs_Matrix(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<Cont_RCA_CA_Status_ListVM>> GetAllCont_RCA_CA_Status_List();
        Task<Cont_RCA_CA_Status_ListVM> PostCont_RCA_CA_Status_List(Cont_RCA_CA_Status_ListVM itemMasterDocList);
        Task<bool> DeleteCont_RCA_CA_Status_List(long itemMasterDocListId);
        Task<IEnumerable<NC_Disp_Decision_ListVM>> GetAllNC_Disp_Decision_List();
        Task<NC_Disp_Decision_ListVM> PostNC_Disp_Decision_List(NC_Disp_Decision_ListVM itemMasterDocList);
        Task<bool> DeleteNC_Disp_Decision_List(long itemMasterDocListId);
        Task<IEnumerable<NC_work_StatusVM>> GetAllNC_work_Status();
        Task<NC_work_StatusVM> PostNC_work_Status(NC_work_StatusVM itemMasterDocList);
        Task<bool> DeleteNC_work_Status(long itemMasterDocListId);
        string HelloWorld();
    }
}
