using CWB.ProductionPlanWO.Domain;
using CWB.ProductionPlanWO.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CWB.ProductionPlanWO.Services
{
    public interface IWOService
    {
        Task<WorkOrdersVM> WorkOrder(WorkOrdersVM workOrdersVM);
        Task<WoSubConSupplierVM> PostWoSubCon(WoSubConSupplierVM workOrdersVM);
        Task<IEnumerable<WorkOrdersVM>> AllWorkOrders(long tenantId);
        Task<IEnumerable<POLogVM>> GetWoPOLogs(long tenantId, long customerOrderId);
        Task<IEnumerable<POLogVM>> GetPOLogs(long tenantId, long poid);
        Task<IEnumerable<WoSubConSupplierVM>> GetAllWoSubCon(long tenantId);
        Task<IEnumerable<WorkOrdersVM>> AllParentChildWo(long ParentWoId, long tenantId);
        Task<IEnumerable<WOSOVM>> GetSoWo(long workOrderId);
        Task<IEnumerable<ProcPlanPartPurChaseRelVM>> GetProcPurchase(long procPlanId);
        Task<List<ProcPlanPartPurChaseRelVM>> PostProcPurchase(List<ProcPlanPartPurChaseRelVM> woso);
        Task<WorkOrdersVM> GetSingleWO(long Id, long tenantId);
        Task<List<WorkOrdersVM>> MultipleWorkOrder(List<WorkOrdersVM> workOrdersVM);
        Task<List<WorkOrdersVM>> UpdateMultipleWorkOrder(List<WorkOrdersVM> workOrdersVM);
        Task<List<WOSOVM>> PostWOSO(List<WOSOVM> woso);
        Task<List<ProcPlanVM>> PostProcPlan(List<ProcPlanVM> proc);
        Task<List<BOMListVM>> PostBomList(List<BOMListVM> bomlist);
        Task<List<BOMTempVM>> BOMTempPost(List<BOMTempVM> bomVm);
        Task<IEnumerable<ProcPlanVM>> AllProcPlan(long tenantId);
        Task<IEnumerable<BOMListVM>> AllBomList(long tenantId);
        Task<List<ProductionPlan_WOVM>> PostProductionPlan_Wo(List<ProductionPlan_WOVM> productions);
        Task<ProductionPlan_WOVM> UpdateProductionPlan_Wo(ProductionPlan_WOVM productions);
        Task<ProductionPlan_WOVM> UpdateHoldProductionPlan_Wo(ProductionPlan_WOVM productions);
        Task<IEnumerable<ProductionPlan_WOVM>> AllProductionWo(long tenantId);
        Task<WOStatusVM> GetWOStatus(long Id);
        Task<bool> DeleteSubCon(long Id);
        Task<bool> DeleteWo(long Id);
        Task<List<ChildWoRelVM>> PostChildWoRel(List<ChildWoRelVM> childWos);
        Task<List<McTimeListVM>> PostMcTimeList(List<McTimeListVM> mcTimeLists);
        Task<IEnumerable<McTimeListVM>> GetAllMcTimeListVMs(long tenantId);
        Task<IEnumerable<PODetailsVM>> GetAllPodetails(long tenantId);
        Task<POStatusVM> GetPOStatus(long Id);
        Task<List<PODetailsVM>> MultiplePODetails(List<PODetailsVM> pODetailsVM);
        Task<List<POHeaderVM>> MultiplePOHeaders(List<POHeaderVM> pOHeaderVMs);
        Task<IEnumerable<Inward_Condn_listVM>> GetAllInward_Condn_list();
        Task<IEnumerable<SetupVariationReasonVM>> GetAllSetupVariationReason();
        Task<IEnumerable<Cust_NC_DecisionVM>> GetAllCust_NC_Decision();
        Task<IEnumerable<Insp_Outcome_DetailsVM>> GetAllInsp_Outcome_Details(long tenantId);
        Task<IEnumerable<Insp_Outcome_ListVM>> GetAllInsp_Outcome_List();
        Task<IEnumerable<Inventory_MasterVM>> GetAllInventory_Master(long tenantId);
        Task<IEnumerable<Inv_Trans_LogVM>> GetAllInvTransLog(long tenantId);
        Task<IEnumerable<Inw_Recpt_DetailsVM>> GetAllInw_Recpt_Details(long tenantId);
        Task<IEnumerable<Inw_Recpt_HeaderVM>> GetAlInw_Recpt_Header(long tenantId);
        Task<IEnumerable<Inw_Recpt_Part_NoVM>> GetAlInw_Recpt_Part_No(long tenantId);
        Task<Insp_Outcome_DetailsVM> PostInsp_Outcome_Details(Insp_Outcome_DetailsVM workOrdersVM);
        Task<Insp_Outcome_ListVM> PostInsp_Outcome_List(Insp_Outcome_ListVM workOrdersVM);
        Task<Inventory_MasterVM> PostInventory_Master(Inventory_MasterVM workOrdersVM);
        Task<Inv_Trans_LogVM> PostInv_Trans_Log(Inv_Trans_LogVM workOrdersVM);
        Task<Inw_Recpt_DetailsVM> PostInw_Recpt_Details(Inw_Recpt_DetailsVM workOrdersVM);
        Task<Inw_Recpt_HeaderVM> PostInw_Recpt_Header(Inw_Recpt_HeaderVM workOrdersVM);
        Task<Inw_Recpt_Part_NoVM> PostInw_Recpt_Part_No(Inw_Recpt_Part_NoVM workOrdersVM);
        Task<Inward_Condn_listVM> PostInward_Condn_list(Inward_Condn_listVM workOrdersVM);
        Task<SetupVariationReasonVM> PostSetupVariationReason(SetupVariationReasonVM workOrdersVM);
        Task<Cust_NC_DecisionVM> PostCust_NC_Decision(Cust_NC_DecisionVM workOrdersVM);
        Task<bool> DeleteInsp_OutcomeDetails(long Id);
        Task<bool> DeleteInventory_Master(long Id);
        Task<bool> DeleteInv_Trans_Log(long Id);
        Task<bool> DeleteInw_Recpt_Details(long Id);
        Task<bool> DeleteInw_Recpt_Header(long Id);
        Task<bool> DeleteInw_Recpt_Part_No(long Id);
        Task<IEnumerable<InwardDocTypeVM>> GetAllInwardDocList(long tenantId);
        Task<InwardDocTypeVM> PostInwardDocList(InwardDocTypeVM itemMasterDocList);
        Task<bool> DeleteInwardDoc(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<LineInspectDocTypeVM>> GetAllLineInspectDocList(long tenantId);
        Task<LineInspectDocTypeVM> PostLineInspectDocList(LineInspectDocTypeVM itemMasterDocList);
        Task<bool> DeleteLineInspectDoc(long itemMasterDocListId, long tenantId);
        Task<bool> DeleteCont_RCA_CA_Log(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<FinalInspectDocTypeVM>> GetAllFinalInspectDocList(long tenantId);
        Task<FinalInspectDocTypeVM> PostFinalInspectDocList(FinalInspectDocTypeVM itemMasterDocList);
        Task<OperationSettingsVM> PostOperationSettings(OperationSettingsVM itemMasterDocList);
        Task<Cont_RCA_CA_LogVM> PostCont_RCA_CA_Log(Cont_RCA_CA_LogVM itemMasterDocList);
        Task<bool> DeleteFinalInspectDoc(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<InspectDocTypeVM>> GetAllInspectDocList(long tenantId);
        Task<InspectDocTypeVM> PostInspectDocList(InspectDocTypeVM itemMasterDocList);
        Task<bool> DeleteInspectDoc(long itemMasterDocListId, long tenantId);

        Task<IEnumerable<RcCaDocTypeVM>> GetAllRcCaDocList(long tenantId);
        Task<RcCaDocTypeVM> PostRcCaDocList(RcCaDocTypeVM itemMasterDocList);
        Task<bool> DeleteRcCaDoc(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<NcLogStatusVM>> GetAllNcLogStatusList();
        Task<IEnumerable<OperationSettingsVM>> GetAllOperationSettings();
        Task<IEnumerable<Cont_RCA_CA_LogVM>> GetAllCont_RCA_CA_Log(long tenantId);
        Task<NcLogStatusVM> PostNcLogStatusList(NcLogStatusVM itemMasterDocList);
        Task<bool> DeleteNcLogStatus(long itemMasterDocListId);

        Task<IEnumerable<NC_Decision_LogVM>> GetAllNC_Decision_Log(long tenantId);
        Task<NC_Decision_LogVM> PostNC_Decision_Log(NC_Decision_LogVM itemMasterDocList);
        Task<bool> DeleteNC_Decision_Log(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<NC_Wk_List_Tmpl_DetVM>> GetAllNC_Wk_List_Tmpl_Det(long tenantId);
        Task<NC_Wk_List_Tmpl_DetVM> PostNC_Wk_List_Tmpl_Det(NC_Wk_List_Tmpl_DetVM itemMasterDocList);
        Task<bool> DeleteNC_Wk_List_Tmpl_Det(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<NC_Disp_Decs_Appl_ListVM>> GetAllNC_Disp_Decs_Appl_List(long tenantId);
        Task<NC_Disp_Decs_Appl_ListVM> PostNC_Disp_Decs_Appl_List(NC_Disp_Decs_Appl_ListVM itemMasterDocList);
        Task<bool> DeleteNC_Disp_Decs_Appl_List(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<NC_Wk_List_Tmpl_HeadVM>> GetAllNC_Wk_List_Tmpl_Head(long tenantId);
        Task<NC_Wk_List_Tmpl_HeadVM> PostNC_Wk_List_Tmpl_Head(NC_Wk_List_Tmpl_HeadVM itemMasterDocList);
        Task<bool> DeleteNC_Wk_List_Tmpl_Head(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<NC_Work_ListVM>> GetAllNC_Work_List(long tenantId);
        Task<NC_Work_ListVM> PostNC_Work_List(NC_Work_ListVM itemMasterDocList);
        Task<bool> DeleteNC_Work_List(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<NC_Wk_List_HeaderVM>> GetAllNC_Wk_List_Header(long tenantId);
        Task<NC_Wk_List_HeaderVM> PostNC_Wk_List_Header(NC_Wk_List_HeaderVM itemMasterDocList);
        Task<bool> DeleteNC_Wk_List_Header(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<Cust_NC_Decs_Matrix_OptVM>> GetAllCust_NC_Decs_Matrix_Opt(long tenantId);
        Task<Cust_NC_Decs_Matrix_OptVM> PostCust_NC_Decs_Matrix_Opt(Cust_NC_Decs_Matrix_OptVM itemMasterDocList);
        Task<bool> DeleteCust_NC_Decs_Matrix_Opt(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<Cust_NC_Decs_MatrixVM>> GetAllCust_NC_Decs_Matrix(long tenantId);
        Task<Cust_NC_Decs_MatrixVM> PostCust_NC_Decs_Matrix(Cust_NC_Decs_MatrixVM itemMasterDocList);
        Task<bool> DeleteCust_NC_Decs_Matrix(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<Cont_RCA_CA_Status_ListVM>> GetAllCont_RCA_CA_Status_List();
        Task<Cont_RCA_CA_Status_ListVM> PostCont_RCA_CA_Status_List(Cont_RCA_CA_Status_ListVM itemMasterDocList);
        Task<bool> DeleteCont_RCA_CA_Status_List(long itemMasterDocListId);
        Task<IEnumerable<NC_Disp_Decision_ListVM>> GetAllNC_Disp_Decision_List();
        Task<NC_Disp_Decision_ListVM> PostNC_Disp_Decision_List(NC_Disp_Decision_ListVM itemMasterDocList);
        Task<bool> DeleteNC_Disp_Decision_List(long itemMasterDocListId);
        Task<IEnumerable<NC_work_StatusVM>> GetAllNC_work_Status();
        Task<NC_work_StatusVM> PostNC_work_Status(NC_work_StatusVM itemMasterDocList);
        Task<bool> DeleteNC_work_Status(long itemMasterDocListId);
        Task<IEnumerable<Mode_ListVM>> GetAllMode_List();
        Task<IEnumerable<Non_Plan_Wk_type_ListVM>> GetAllNon_Plan_Wk_type_List();
        Task<IEnumerable<Time_Slot_AllocationVM>> GetAllTime_Slot_Allocation();
        Task<IEnumerable<Mc_Not_Avl_ReasonVM>> GetAllMc_Not_Avl_Reason(long tenantId);
        Task<Mc_Not_Avl_ReasonVM> PostMc_Not_Avl_Reason(Mc_Not_Avl_ReasonVM itemMasterDocList);
        Task<IEnumerable<Mc_Timeslot_ListVM>> GetAllMc_Timeslot_List(long tenantId);
        Task<IEnumerable<Mc_Timeslot_ListVM>> GetAllMc_Timeslot_ListByMcWait(long mcWaitId, long tenantId);
        Task<Mc_Timeslot_ListVM> PostMc_Timeslot_List(Mc_Timeslot_ListVM itemMasterDocList);
        Task<bool> DeleteMc_Timeslot_List(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<TempMc_Timeslot_ListVM>> GetAllTempMc_Timeslot_List(long tenantId);
        Task<IEnumerable<TempMc_Timeslot_ListVM>> GetAllTempMc_Timeslot_ListByMcWait(long mcWaitId, long tenantId);
        Task<TempMc_Timeslot_ListVM> PostTempMc_Timeslot_List(TempMc_Timeslot_ListVM itemMasterDocList);
        Task<bool> DeleteTempMc_Timeslot_List(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<Non_Plan_Wk_ListVM>> GetAllNon_Plan_Wk_List(long tenantId);
        Task<Non_Plan_Wk_ListVM> PostNon_Plan_Wk_List(Non_Plan_Wk_ListVM itemMasterDocList);
        Task<bool> DeleteNon_Plan_Wk_List(long itemMasterDocListId,long tenantId);
        Task<IEnumerable<WO_Wait_ListVM>> GetAllWO_Wait_List(long tenantId);
        Task<WO_Wait_ListVM> PostWO_Wait_List(WO_Wait_ListVM itemMasterDocList);
        Task<bool> DeleteWO_Wait_List(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<TempWO_Wait_ListVM>> GetAllTempWO_Wait_List(long tenantId);
        Task<TempWO_Wait_ListVM> PostTempWO_Wait_List(TempWO_Wait_ListVM itemMasterDocList);
        Task<bool> DeleteTempWO_Wait_List(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<WO_Bookout_LogVM>> GetAllWO_Bookout_Log(long tenantId);
        Task<WO_Bookout_LogVM> PostWO_Bookout_Log(WO_Bookout_LogVM itemMasterDocList);
        Task<bool> DeleteWO_Bookout_Log(long itemMasterDocListId);
        Task<IEnumerable<Timeslot_SettingVM>> GetAllTimeslot_Setting(long tenantId);
        Task<Timeslot_SettingVM> PostTimeslot_Setting(Timeslot_SettingVM itemMasterDocList);
        Task<bool> DeleteTimeslot_Setting(long itemMasterDocListId);
        Task<IEnumerable<Timeslot_ListVM>> GetAllTimeslot_List(long tenantId);
        Task<Timeslot_ListVM> PostTimeslot_List(Timeslot_ListVM itemMasterDocList);
        Task<bool> DeleteTimeslot_List(long itemMasterDocListId,long tenantId);
        Task<IEnumerable<Rwk_ListVM>> GetAllRwk_List(long tenantId);
        Task<Rwk_ListVM> PostRwk_List(Rwk_ListVM itemMasterDocList);
        Task<bool> DeleteRwk_List(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<Opr_ListVM>> GetAllOpr_List(long tenantId);
        Task<Opr_ListVM> PostOpr_List(Opr_ListVM itemMasterDocList);
        Task<bool> DeleteOpr_List(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<TempOpr_ListVM>> GetAllTempOpr_List(long tenantId);
        Task<TempOpr_ListVM> PostTempOpr_List(TempOpr_ListVM itemMasterDocList);
        Task<bool> DeleteTempOpr_List(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<Shop_Insp_LogVM>> GetAllShop_Insp_Log(long tenantId);
        Task<Shop_Insp_LogVM> PostShop_Insp_Log(Shop_Insp_LogVM itemMasterDocList);
        Task<bool> DeleteShop_Insp_Log(long itemMasterDocListId,long tenantId);
        Task<IEnumerable<SubCon_ListVM>> GetAllSubCon_List(long tenantId);
        Task<SubCon_ListVM> PostSubCon_List(SubCon_ListVM itemMasterDocList);
        Task<bool> DeleteSubCon_List(long itemMasterDocListId,long tenantId);
        Task<IEnumerable<TempSubCon_ListVM>> GetAllTempSubCon_List(long tenantId);
        Task<TempSubCon_ListVM> PostTempSubCon_List(TempSubCon_ListVM itemMasterDocList);
        Task<bool> DeleteTempSubCon_List(long itemMasterDocListId,long tenantId);
        Task<IEnumerable<Mc_Wait_ListVM>> GetAllMc_Wait_List(long tenantId);
        Task<IEnumerable<Mc_Wait_ListVM>> GetAllMc_Wait_ListByMcWait(long mcWaitId, long tenantId);
        Task<Mc_Wait_ListVM> PostMc_Wait_List(Mc_Wait_ListVM itemMasterDocList);
        Task<bool> DeleteMc_Wait_List(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<TempMc_Wait_ListVM>> GetAllTempMc_Wait_List(long tenantId);
        Task<IEnumerable<TempMc_Wait_ListVM>> GetAllTempMc_Wait_ListByMcWait(long mcWaitId, long tenantId);
        Task<TempMc_Wait_ListVM> PostTempMc_Wait_List(TempMc_Wait_ListVM itemMasterDocList);
        Task<bool> DeleteTempMc_Wait_List(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<Matl_Issue_ListVM>> GetAllMatl_Issue_List(long tenantId);
        Task<Matl_Issue_ListVM> PostMatl_Issue_List(Matl_Issue_ListVM itemMasterDocList);
        Task<bool> DeleteMatl_Issue_List(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<Matl_Issue_SettingsVM>> GetAllMatl_Issue_Settings(long tenantId);
        Task<Matl_Issue_SettingsVM> PostMatl_Issue_Settings(Matl_Issue_SettingsVM itemMasterDocList);
        Task<bool> DeleteMatl_Issue_Settings(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<DispatchDetailsVM>> GetAllDispatchDetails(long tenantId);
        Task<DispatchDetailsVM> PostDispatchDetails(DispatchDetailsVM itemMasterDocList);
        Task<bool> DeleteDispatchDetails(long itemMasterDocListId, long tenantId);
        Task<IEnumerable<DispatchQntyVM>> GetAllDispatchQnty(long tenantId);
        Task<DispatchQntyVM> PostDispatchQnty(DispatchQntyVM itemMasterDocList);
        Task<bool> DeleteDispatchQnty(long itemMasterDocListId, long tenantId);

        string HelloWorld();
    }
}
