using AutoMapper;
using CWB.ProductionPlanWO.Domain;
using CWB.ProductionPlanWO.ViewModels;

namespace CWB.ProductionPlanWO.Utils
{
    public class AutoMapping : Profile
    {
        public AutoMapping()
        {
            CreateMap<WorkOrders, WorkOrdersVM>()
               .ForMember(m => m.WOID, m => m.MapFrom(src => src.Id))
               .ForMember(m => m.SalesOrderId, m => m.MapFrom(src => src.SalesOrderId))
               .ForMember(m => m.WONumber, m => m.MapFrom(src => src.WONumber))
               .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
               .ForMember(m => m.PartType, m => m.MapFrom(src => src.PartType))
               .ForMember(m => m.Parentlevel, m => m.MapFrom(src => src.Parentlevel))
               .ForMember(m => m.CalcWOQty, m => m.MapFrom(src => src.CalcWOQty))
               .ForMember(m => m.BuildToStock, m => m.MapFrom(src => src.BuildToStock))
               .ForMember(m => m.PlanCompletionDate, m => m.MapFrom(src => src.PlanCompletionDate))
               .ForMember(m => m.SoComplDate, m => m.MapFrom(src => src.SoComplDate))
               .ForMember(m => m.Status, m => m.MapFrom(src => src.Status))
               .ForMember(m => m.RoutingId, m => m.MapFrom(src => src.RoutingId))
               .ForMember(m => m.StartingOpNo, m => m.MapFrom(src => src.StartingOpNo))
               .ForMember(m => m.EndingOpNo, m => m.MapFrom(src => src.EndingOpNo))
               .ForMember(m => m.For_Ref, m => m.MapFrom(src => src.For_Ref))
               .ForMember(m => m.ReloadOption, m => m.MapFrom(src => src.ReloadOption))
               .ForMember(m => m.Active, m => m.MapFrom(src => src.Active))
               .ForMember(m => m.ParentWoId, m => m.MapFrom(src => src.ParentWoId))
               .ForMember(m => m.WODate, m => m.MapFrom(src => src.WODate));

            CreateMap<WorkOrdersVM, WorkOrders>()
               .ForMember(m => m.Id, m => m.MapFrom(src => src.WOID))
               .ForMember(m => m.SalesOrderId, m => m.MapFrom(src => src.SalesOrderId))
               .ForMember(m => m.WONumber, m => m.MapFrom(src => src.WONumber))
               .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
               .ForMember(m => m.PartType, m => m.MapFrom(src => src.PartType))
               .ForMember(m => m.Parentlevel, m => m.MapFrom(src => src.Parentlevel))
               .ForMember(m => m.CalcWOQty, m => m.MapFrom(src => src.CalcWOQty))
               .ForMember(m => m.BuildToStock, m => m.MapFrom(src => src.BuildToStock))
               .ForMember(m => m.PlanCompletionDate, m => m.MapFrom(src => src.PlanCompletionDate))
               .ForMember(m => m.SoComplDate, m => m.MapFrom(src => src.SoComplDate))
               .ForMember(m => m.Status, m => m.MapFrom(src => src.Status))
               .ForMember(m => m.WODate, m => m.MapFrom(src => src.WODate))
               .ForMember(m => m.RoutingId, m => m.MapFrom(src => src.RoutingId))
               .ForMember(m => m.StartingOpNo, m => m.MapFrom(src => src.StartingOpNo))
               .ForMember(m => m.EndingOpNo, m => m.MapFrom(src => src.EndingOpNo))
               .ForMember(m => m.For_Ref, m => m.MapFrom(src => src.For_Ref))
               .ForMember(m => m.ReloadOption, m => m.MapFrom(src => src.ReloadOption))
               .ForMember(m => m.Active, m => m.MapFrom(src => src.Active))
               .ForMember(m => m.ParentWoId, m => m.MapFrom(src => src.ParentWoId))
               .ForMember(m => m.WODate, m => m.MapFrom(src => src.WODate));

            CreateMap<Cust_NC_Decs_MatrixVM, Cust_NC_Decs_Matrix>()
               .ForMember(m => m.Id, m => m.MapFrom(src => src.Cust_NC_Decs_MatrixId))
               .ForMember(m => m.Cust_Request_Id, m => m.MapFrom(src => src.Cust_Request_Id))
               .ForMember(m => m.Cust_Feedback_Id, m => m.MapFrom(src => src.Cust_Feedback_Id))
               .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<Cust_NC_Decs_Matrix, Cust_NC_Decs_MatrixVM>()
               .ForMember(m => m.Cust_NC_Decs_MatrixId, m => m.MapFrom(src => src.Id))
               .ForMember(m => m.Cust_Request_Id, m => m.MapFrom(src => src.Cust_Request_Id))
               .ForMember(m => m.Cust_Feedback_Id, m => m.MapFrom(src => src.Cust_Feedback_Id))
               .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<Cust_NC_Decs_Matrix_OptVM, Cust_NC_Decs_Matrix_Opt>()
               .ForMember(m => m.Id, m => m.MapFrom(src => src.Cust_NC_Decs_Matrix_OptId))
               .ForMember(m => m.Cust_NC_Decs_Matrix_Id, m => m.MapFrom(src => src.Cust_NC_Decs_Matrix_Id))
               .ForMember(m => m.NC_Disp_Decision_Id, m => m.MapFrom(src => src.NC_Disp_Decision_Id))
               .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<Cust_NC_Decs_Matrix_Opt, Cust_NC_Decs_Matrix_OptVM>()
               .ForMember(m => m.Cust_NC_Decs_Matrix_OptId, m => m.MapFrom(src => src.Id))
               .ForMember(m => m.Cust_NC_Decs_Matrix_Id, m => m.MapFrom(src => src.Cust_NC_Decs_Matrix_Id))
               .ForMember(m => m.NC_Disp_Decision_Id, m => m.MapFrom(src => src.NC_Disp_Decision_Id))
               .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<WOSOVM, WOSO>()
               .ForMember(m => m.Id, m => m.MapFrom(src => src.WOSOId))
               .ForMember(m => m.SalesOrderId, m => m.MapFrom(src => src.SalesOrderId))
               .ForMember(m => m.Active, m => m.MapFrom(src => src.Active))
               .ForMember(m => m.WorkOrderId, m => m.MapFrom(src => src.WorkOrderId));

            CreateMap<WOSO, WOSOVM>()
               .ForMember(m => m.WOSOId, m => m.MapFrom(src => src.Id))
               .ForMember(m => m.SalesOrderId, m => m.MapFrom(src => src.SalesOrderId))
               .ForMember(m => m.Active, m => m.MapFrom(src => src.Active))
               .ForMember(m => m.WorkOrderId, m => m.MapFrom(src => src.WorkOrderId));
            CreateMap<ProcPlanPartPurChaseRelVM, ProcPlanPartPurChaseRel>()
               .ForMember(m => m.Id, m => m.MapFrom(src => src.ProcPlanPartPurChaseRelId))
               .ForMember(m => m.PartPurchaseId, m => m.MapFrom(src => src.PartPurchaseId))
               .ForMember(m => m.Active, m => m.MapFrom(src => src.Active))
               .ForMember(m => m.LeadTime, m => m.MapFrom(src => src.LeadTime))
               .ForMember(m => m.ProcPlanId, m => m.MapFrom(src => src.ProcPlanId));

            CreateMap<ProcPlanPartPurChaseRel, ProcPlanPartPurChaseRelVM>()
               .ForMember(m => m.ProcPlanPartPurChaseRelId, m => m.MapFrom(src => src.Id))
               .ForMember(m => m.PartPurchaseId, m => m.MapFrom(src => src.PartPurchaseId))
               .ForMember(m => m.Active, m => m.MapFrom(src => src.Active))
               .ForMember(m => m.LeadTime, m => m.MapFrom(src => src.LeadTime))
               .ForMember(m => m.ProcPlanId, m => m.MapFrom(src => src.ProcPlanId));

            CreateMap<BOMTempVM, BOMTemp>()
              .ForMember(m => m.Id, m => m.MapFrom(src => src.BomTempId))
              .ForMember(m => m.WorkOrderId, m => m.MapFrom(src => src.WorkOrderId))
              .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
              .ForMember(m => m.PartType, m => m.MapFrom(src => src.PartType))
              .ForMember(m => m.Parentlevel, m => m.MapFrom(src => src.Parentlevel));

            CreateMap<BOMTemp, BOMTempVM>()
             .ForMember(m => m.BomTempId, m => m.MapFrom(src => src.Id))
             .ForMember(m => m.WorkOrderId, m => m.MapFrom(src => src.WorkOrderId))
             .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
             .ForMember(m => m.PartType, m => m.MapFrom(src => src.PartType))
             .ForMember(m => m.Parentlevel, m => m.MapFrom(src => src.Parentlevel));

            CreateMap<ProcPlanVM, ProcPlan>()
            .ForMember(m => m.Id, m => m.MapFrom(src => src.ProcPlanId))
            .ForMember(m => m.Reference, m => m.MapFrom(src => src.Reference))
            .ForMember(m => m.TestData, m => m.MapFrom(src => src.TestData))
            .ForMember(m => m.For_Ref, m => m.MapFrom(src => src.For_Ref))
            .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
            .ForMember(m => m.WorkOrderId, m => m.MapFrom(src => src.WorkOrderId))
            .ForMember(m => m.PartType, m => m.MapFrom(src => src.PartType))
            .ForMember(m => m.UOMId, m => m.MapFrom(src => src.UOMId))
            .ForMember(m => m.Calc_Proc_Qnty, m => m.MapFrom(src => src.Calc_Proc_Qnty))
            .ForMember(m => m.AddnOtyUser, m => m.MapFrom(src => src.AddnOtyUser))
            .ForMember(m => m.Plan_Proc_Qnty, m => m.MapFrom(src => src.Plan_Proc_Qnty))
            .ForMember(m => m.PlanReceiptDate, m => m.MapFrom(src => src.PlanReceiptDate))
            .ForMember(m => m.CalcReceiptDate, m => m.MapFrom(src => src.CalcReceiptDate))
            .ForMember(m => m.CriticalPart, m => m.MapFrom(src => src.CriticalPart))
            .ForMember(m => m.Changed, m => m.MapFrom(src => src.Changed))
            .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<ProcPlan, ProcPlanVM> ()
            .ForMember(m => m.ProcPlanId, m => m.MapFrom(src => src.Id))
            .ForMember(m => m.Reference, m => m.MapFrom(src => src.Reference))
            .ForMember(m => m.TestData, m => m.MapFrom(src => src.TestData))
            .ForMember(m => m.For_Ref, m => m.MapFrom(src => src.For_Ref))
            .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
            .ForMember(m => m.WorkOrderId, m => m.MapFrom(src => src.WorkOrderId))
            .ForMember(m => m.PartType, m => m.MapFrom(src => src.PartType))
            .ForMember(m => m.UOMId, m => m.MapFrom(src => src.UOMId))
            .ForMember(m => m.Calc_Proc_Qnty, m => m.MapFrom(src => src.Calc_Proc_Qnty))
            .ForMember(m => m.AddnOtyUser, m => m.MapFrom(src => src.AddnOtyUser))
            .ForMember(m => m.Plan_Proc_Qnty, m => m.MapFrom(src => src.Plan_Proc_Qnty))
            .ForMember(m => m.PlanReceiptDate, m => m.MapFrom(src => src.PlanReceiptDate))
            .ForMember(m => m.CalcReceiptDate, m => m.MapFrom(src => src.CalcReceiptDate))
            .ForMember(m => m.CriticalPart, m => m.MapFrom(src => src.CriticalPart))
            .ForMember(m => m.Changed, m => m.MapFrom(src => src.Changed))
            .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));


            CreateMap<POLog, POLogVM>()
                .ForMember(m => m.POLogId, m => m.MapFrom(src => src.Id))
                .ForMember(m => m.PODate, m => m.MapFrom(src => src.CreationDate))
                .ForMember(m => m.CustomerOrderId, m => m.MapFrom(src => src.CustomerOrderId))
                .ForMember(m => m.SalesOrderId, m => m.MapFrom(src => src.SalesOrderId))
                .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
                .ForMember(m => m.User, m => m.MapFrom(src => src.User))
                .ForMember(m => m.NewValue, m => m.MapFrom(src => src.NewValue))
                .ForMember(m => m.OldValue, m => m.MapFrom(src => src.OldValue))
                .ForMember(m => m.Comment, m => m.MapFrom(src => src.Comment))
                .ForMember(m => m.Event, m => m.MapFrom(src => src.Event));
            CreateMap<POLogVM, POLog>()
                .ForMember(m => m.Id, m => m.MapFrom(src => src.POLogId))
                .ForMember(m => m.CustomerOrderId, m => m.MapFrom(src => src.CustomerOrderId))
                .ForMember(m => m.SalesOrderId, m => m.MapFrom(src => src.SalesOrderId))
                .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
                .ForMember(m => m.User, m => m.MapFrom(src => src.User))
                .ForMember(m => m.NewValue, m => m.MapFrom(src => src.NewValue))
                .ForMember(m => m.OldValue, m => m.MapFrom(src => src.OldValue))
                .ForMember(m => m.Comment, m => m.MapFrom(src => src.Comment))
                .ForMember(m => m.Event, m => m.MapFrom(src => src.Event));

            CreateMap<BOMListVM, BOMList>()
            .ForMember(m => m.Id, m => m.MapFrom(src => src.BomListId))
            .ForMember(m => m.ParentWoId, m => m.MapFrom(src => src.ParentWoId))
            .ForMember(m => m.Child_Part_No_ID, m => m.MapFrom(src => src.Child_Part_No_ID))
            .ForMember(m => m.Child_Part_No_Type, m => m.MapFrom(src => src.Child_Part_No_Type))
            .ForMember(m => m.Manf_RM_Link_ID, m => m.MapFrom(src => src.Manf_RM_Link_ID))
            .ForMember(m => m.Calc_Qnty, m => m.MapFrom(src => src.Calc_Qnty))
            .ForMember(m => m.QtyOnHand, m => m.MapFrom(src => src.QtyOnHand))
            .ForMember(m => m.Plan_Qnty, m => m.MapFrom(src => src.Plan_Qnty))
            .ForMember(m => m.Plan_Start_Dt, m => m.MapFrom(src => src.Plan_Start_Dt))
            .ForMember(m => m.Plan_Compl_Dt, m => m.MapFrom(src => src.Plan_Compl_Dt))
            .ForMember(m => m.PlanReceiptDate, m => m.MapFrom(src => src.PlanReceiptDate))
            .ForMember(m => m.CalcReceiptDate, m => m.MapFrom(src => src.CalcReceiptDate))
            .ForMember(m => m.Manf_Days_Avl, m => m.MapFrom(src => src.Manf_Days_Avl))
            .ForMember(m => m.Manf_Days_Reqd, m => m.MapFrom(src => src.Manf_Days_Reqd))
            .ForMember(m => m.CriticalPart, m => m.MapFrom(src => src.CriticalPart))
            .ForMember(m => m.AddnQtyUser, m => m.MapFrom(src => src.AddnQtyUser))
            .ForMember(m => m.ChildWoId, m => m.MapFrom(src => src.ChildWoId))
            .ForMember(m => m.TestData, m => m.MapFrom(src => src.TestData))
            .ForMember(m => m.ProcPlanId, m => m.MapFrom(src => src.ProcPlanId))
            .ForMember(m => m.SaNestLevel, m => m.MapFrom(src => src.SaNestLevel))
            .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<BOMList, BOMListVM>()
             .ForMember(m => m.BomListId, m => m.MapFrom(src => src.Id))
             .ForMember(m => m.ParentWoId, m => m.MapFrom(src => src.ParentWoId))
             .ForMember(m => m.Child_Part_No_ID, m => m.MapFrom(src => src.Child_Part_No_ID))
             .ForMember(m => m.Child_Part_No_Type, m => m.MapFrom(src => src.Child_Part_No_Type))
             .ForMember(m => m.Manf_RM_Link_ID, m => m.MapFrom(src => src.Manf_RM_Link_ID))
             .ForMember(m => m.Calc_Qnty, m => m.MapFrom(src => src.Calc_Qnty))
             .ForMember(m => m.QtyOnHand, m => m.MapFrom(src => src.QtyOnHand))
             .ForMember(m => m.Plan_Qnty, m => m.MapFrom(src => src.Plan_Qnty))
             .ForMember(m => m.Plan_Start_Dt, m => m.MapFrom(src => src.Plan_Start_Dt))
             .ForMember(m => m.Plan_Compl_Dt, m => m.MapFrom(src => src.Plan_Compl_Dt))
             .ForMember(m => m.PlanReceiptDate, m => m.MapFrom(src => src.PlanReceiptDate))
             .ForMember(m => m.CalcReceiptDate, m => m.MapFrom(src => src.CalcReceiptDate))
             .ForMember(m => m.Manf_Days_Avl, m => m.MapFrom(src => src.Manf_Days_Avl))
             .ForMember(m => m.Manf_Days_Reqd, m => m.MapFrom(src => src.Manf_Days_Reqd))
             .ForMember(m => m.CriticalPart, m => m.MapFrom(src => src.CriticalPart))
             .ForMember(m => m.AddnQtyUser, m => m.MapFrom(src => src.AddnQtyUser))
             .ForMember(m => m.ChildWoId, m => m.MapFrom(src => src.ChildWoId))
             .ForMember(m => m.TestData, m => m.MapFrom(src => src.TestData))
             .ForMember(m => m.ProcPlanId, m => m.MapFrom(src => src.ProcPlanId))
             .ForMember(m => m.SaNestLevel, m => m.MapFrom(src => src.SaNestLevel))
             .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));


            CreateMap<ProductionPlan_WO, ProductionPlan_WOVM>()
               .ForMember(m => m.ProductionPlanId, m => m.MapFrom(src => src.Id))
               .ForMember(m => m.PPNumber, m => m.MapFrom(src => src.PPNumber))
               .ForMember(m => m.WoId, m => m.MapFrom(src => src.WoId))
               .ForMember(m => m.ParentWoId, m => m.MapFrom(src => src.ParentWoId))
               .ForMember(m => m.SalesOrderId, m => m.MapFrom(src => src.SalesOrderId))
               .ForMember(m => m.WONumber, m => m.MapFrom(src => src.WONumber))
               .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
               .ForMember(m => m.PartType, m => m.MapFrom(src => src.PartType))
               .ForMember(m => m.Parentlevel, m => m.MapFrom(src => src.Parentlevel))
               .ForMember(m => m.CalcWOQty, m => m.MapFrom(src => src.CalcWOQty))
               .ForMember(m => m.BuildToStock, m => m.MapFrom(src => src.BuildToStock))
               .ForMember(m => m.PlanCompletionDate, m => m.MapFrom(src => src.PlanCompletionDate))
               .ForMember(m => m.SoComplDate, m => m.MapFrom(src => src.SoComplDate))
               .ForMember(m => m.Status, m => m.MapFrom(src => src.Status))
               .ForMember(m => m.RoutingId, m => m.MapFrom(src => src.RoutingId))
               .ForMember(m => m.StartingOpNo, m => m.MapFrom(src => src.StartingOpNo))
               .ForMember(m => m.EndingOpNo, m => m.MapFrom(src => src.EndingOpNo))
               .ForMember(m => m.For_Ref, m => m.MapFrom(src => src.For_Ref))
               .ForMember(m => m.Active, m => m.MapFrom(src => src.Active))
               .ForMember(m => m.WODate, m => m.MapFrom(src => src.WODate));

            CreateMap<ProductionPlan_WOVM, ProductionPlan_WO>()
               .ForMember(m => m.Id, m => m.MapFrom(src => src.ProductionPlanId))
               .ForMember(m => m.PPNumber, m => m.MapFrom(src => src.PPNumber))
               .ForMember(m => m.WoId, m => m.MapFrom(src => src.WoId))
               .ForMember(m => m.ParentWoId, m => m.MapFrom(src => src.ParentWoId))
               .ForMember(m => m.SalesOrderId, m => m.MapFrom(src => src.SalesOrderId))
               .ForMember(m => m.WONumber, m => m.MapFrom(src => src.WONumber))
               .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
               .ForMember(m => m.PartType, m => m.MapFrom(src => src.PartType))
               .ForMember(m => m.Parentlevel, m => m.MapFrom(src => src.Parentlevel))
               .ForMember(m => m.CalcWOQty, m => m.MapFrom(src => src.CalcWOQty))
               .ForMember(m => m.BuildToStock, m => m.MapFrom(src => src.BuildToStock))
               .ForMember(m => m.PlanCompletionDate, m => m.MapFrom(src => src.PlanCompletionDate))
               .ForMember(m => m.SoComplDate, m => m.MapFrom(src => src.SoComplDate))
               .ForMember(m => m.Status, m => m.MapFrom(src => src.Status))
               .ForMember(m => m.RoutingId, m => m.MapFrom(src => src.RoutingId))
               .ForMember(m => m.StartingOpNo, m => m.MapFrom(src => src.StartingOpNo))
               .ForMember(m => m.EndingOpNo, m => m.MapFrom(src => src.EndingOpNo))
               .ForMember(m => m.For_Ref, m => m.MapFrom(src => src.For_Ref))
               .ForMember(m => m.Active, m => m.MapFrom(src => src.Active))
               .ForMember(m => m.WODate, m => m.MapFrom(src => src.WODate));


            CreateMap<WOStatusVM, WOStatus>()
               .ForMember(m => m.Id, m => m.MapFrom(src => src.StatusId))
               .ForMember(m => m.Status, m => m.MapFrom(src => src.Status));

            CreateMap<WOStatus, WOStatusVM>()
               .ForMember(m => m.StatusId, m => m.MapFrom(src => src.Id))
               .ForMember(m => m.Status, m => m.MapFrom(src => src.Status));

            CreateMap<ChildWoRelVM, ChildWoRel>()
               .ForMember(m => m.Id, m => m.MapFrom(src => src.ChildWoRelId))
               .ForMember(m => m.WoId, m => m.MapFrom(src => src.WoId))
               .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
               .ForMember(m => m.Qnty, m => m.MapFrom(src => src.Qnty))
               .ForMember(m => m.CameFrom, m => m.MapFrom(src => src.CameFrom));

            CreateMap<ChildWoRel, ChildWoRelVM>()
                .ForMember(m => m.ChildWoRelId, m => m.MapFrom(src => src.Id))
                .ForMember(m => m.WoId, m => m.MapFrom(src => src.WoId))
                .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
                .ForMember(m => m.Qnty, m => m.MapFrom(src => src.Qnty))
                .ForMember(m => m.CameFrom, m => m.MapFrom(src => src.CameFrom));

            CreateMap<McTimeListVM, McTimeList>()
           .ForMember(m => m.Id, m => m.MapFrom(src => src.McTimeListId))
           .ForMember(m => m.WoId, m => m.MapFrom(src => src.WoId))
           .ForMember(m => m.Routing_StepId, m => m.MapFrom(src => src.Routing_StepId))
           .ForMember(m => m.CompanyId, m => m.MapFrom(src => src.CompanyId))
           .ForMember(m => m.MachineId, m => m.MapFrom(src => src.MachineId))
           .ForMember(m => m.MachineTypeId, m => m.MapFrom(src => src.MachineTypeId))
           .ForMember(m => m.PlanQnty, m => m.MapFrom(src => src.PlanQnty))
           .ForMember(m => m.TotalPlanTime, m => m.MapFrom(src => src.TotalPlanTime))
           .ForMember(m => m.McPlanStartTime, m => m.MapFrom(src => src.McPlanStartTime))
           .ForMember(m => m.McPlanEndTime, m => m.MapFrom(src => src.McPlanEndTime))
           .ForMember(m => m.McActStartTime, m => m.MapFrom(src => src.McActStartTime))
           .ForMember(m => m.McActEndTime, m => m.MapFrom(src => src.McActEndTime))
           .ForMember(m => m.ActQnty, m => m.MapFrom(src => src.ActQnty))
           .ForMember(m => m.TotalActTime, m => m.MapFrom(src => src.TotalActTime))
           .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<McTimeList, McTimeListVM>()
            .ForMember(m => m.McTimeListId, m => m.MapFrom(src => src.Id))
           .ForMember(m => m.WoId, m => m.MapFrom(src => src.WoId))
           .ForMember(m => m.Routing_StepId, m => m.MapFrom(src => src.Routing_StepId))
           .ForMember(m => m.CompanyId, m => m.MapFrom(src => src.CompanyId))
           .ForMember(m => m.MachineId, m => m.MapFrom(src => src.MachineId))
           .ForMember(m => m.MachineTypeId, m => m.MapFrom(src => src.MachineTypeId))
           .ForMember(m => m.PlanQnty, m => m.MapFrom(src => src.PlanQnty))
           .ForMember(m => m.TotalPlanTime, m => m.MapFrom(src => src.TotalPlanTime))
           .ForMember(m => m.McPlanStartTime, m => m.MapFrom(src => src.McPlanStartTime))
           .ForMember(m => m.McPlanEndTime, m => m.MapFrom(src => src.McPlanEndTime))
           .ForMember(m => m.McActStartTime, m => m.MapFrom(src => src.McActStartTime))
           .ForMember(m => m.McActEndTime, m => m.MapFrom(src => src.McActEndTime))
           .ForMember(m => m.ActQnty, m => m.MapFrom(src => src.ActQnty))
           .ForMember(m => m.TotalActTime, m => m.MapFrom(src => src.TotalActTime))
           .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));



            CreateMap<POStatusVM, POStatus>()
               .ForMember(m => m.Id, m => m.MapFrom(src => src.StatusId))
               .ForMember(m => m.Status, m => m.MapFrom(src => src.Status));

            CreateMap<POStatus, POStatusVM>()
               .ForMember(m => m.StatusId, m => m.MapFrom(src => src.Id))
               .ForMember(m => m.Status, m => m.MapFrom(src => src.Status));

            CreateMap<PODetailsVM, PODetails>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.PoDetailsId))
          .ForMember(m => m.POReference, m => m.MapFrom(src => src.POReference))
          .ForMember(m => m.ProcPlanId, m => m.MapFrom(src => src.ProcPlanId))
          .ForMember(m => m.AddHocPO, m => m.MapFrom(src => src.AddHocPO))
          .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
          .ForMember(m => m.PoQnty, m => m.MapFrom(src => src.PoQnty))
          .ForMember(m => m.PoDate, m => m.MapFrom(src => src.PoDate))
          .ForMember(m => m.CompanyId, m => m.MapFrom(src => src.CompanyId))
          .ForMember(m => m.PlanPoReceiptDate, m => m.MapFrom(src => src.PlanPoReceiptDate))
          .ForMember(m => m.PoSent, m => m.MapFrom(src => src.PoSent))
          .ForMember(m => m.PoQntyRecd, m => m.MapFrom(src => src.PoQntyRecd))
          .ForMember(m => m.Status, m => m.MapFrom(src => src.Status))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<PODetails, PODetailsVM>()
            .ForMember(m => m.PoDetailsId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.POReference, m => m.MapFrom(src => src.POReference))
          .ForMember(m => m.ProcPlanId, m => m.MapFrom(src => src.ProcPlanId))
          .ForMember(m => m.AddHocPO, m => m.MapFrom(src => src.AddHocPO))
          .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
          .ForMember(m => m.PoQnty, m => m.MapFrom(src => src.PoQnty))
          .ForMember(m => m.PoDate, m => m.MapFrom(src => src.PoDate))
          .ForMember(m => m.CompanyId, m => m.MapFrom(src => src.CompanyId))
          .ForMember(m => m.PlanPoReceiptDate, m => m.MapFrom(src => src.PlanPoReceiptDate))
          .ForMember(m => m.PoSent, m => m.MapFrom(src => src.PoSent))
          .ForMember(m => m.PoQntyRecd, m => m.MapFrom(src => src.PoQntyRecd))
          .ForMember(m => m.Status, m => m.MapFrom(src => src.Status))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));


            CreateMap<POHeaderVM, POHeader>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.PoHeaderId))
          .ForMember(m => m.PoDetailsId, m => m.MapFrom(src => src.PoDetailsId))
          .ForMember(m => m.SupplierId, m => m.MapFrom(src => src.SupplierId))
          .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<POHeader, POHeaderVM>()
          .ForMember(m => m.PoHeaderId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.PoDetailsId, m => m.MapFrom(src => src.PoDetailsId))
          .ForMember(m => m.SupplierId, m => m.MapFrom(src => src.SupplierId))
          .ForMember(m => m.PartId, m => m.MapFrom(src => src.PartId))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<WoSubConSupplierVM, WoSubConSupplier>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.WoSubConSupplierId))
          .ForMember(m => m.WoId, m => m.MapFrom(src => src.WoId))
          .ForMember(m => m.SubConId, m => m.MapFrom(src => src.ProcPlanId))
          .ForMember(m => m.SupplierId, m => m.MapFrom(src => src.SupplierId))
          .ForMember(m => m.Qnty, m => m.MapFrom(src => src.Qnty))
          .ForMember(m => m.ProcPrice, m => m.MapFrom(src => src.ProcPrice))
          .ForMember(m => m.AddnInfo, m => m.MapFrom(src => src.AddnInfo))
          .ForMember(m => m.RecieptDate, m => m.MapFrom(src => src.RecieptDate))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<WoSubConSupplier, WoSubConSupplierVM>()
          .ForMember(m => m.WoSubConSupplierId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.WoId, m => m.MapFrom(src => src.WoId))
          .ForMember(m => m.ProcPlanId, m => m.MapFrom(src => src.SubConId))
          .ForMember(m => m.SupplierId, m => m.MapFrom(src => src.SupplierId))
          .ForMember(m => m.Qnty, m => m.MapFrom(src => src.Qnty))
          .ForMember(m => m.ProcPrice, m => m.MapFrom(src => src.ProcPrice))
          .ForMember(m => m.AddnInfo, m => m.MapFrom(src => src.AddnInfo))
          .ForMember(m => m.RecieptDate, m => m.MapFrom(src => src.RecieptDate))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            
            CreateMap<Inw_Recpt_Part_NoVM, Inw_Recpt_Part_No>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.Inw_Recpt_Part_No_Id))
          .ForMember(m => m.PO_Details_Id, m => m.MapFrom(src => src.PO_Details_Id))
          .ForMember(m => m.Release_Insp, m => m.MapFrom(src => src.Release_Insp))
          .ForMember(m => m.Insp_Complete, m => m.MapFrom(src => src.Insp_Complete))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<Inw_Recpt_Part_No, Inw_Recpt_Part_NoVM>()
          .ForMember(m => m.Inw_Recpt_Part_No_Id, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.PO_Details_Id, m => m.MapFrom(src => src.PO_Details_Id))
          .ForMember(m => m.Release_Insp, m => m.MapFrom(src => src.Release_Insp))
          .ForMember(m => m.Insp_Complete, m => m.MapFrom(src => src.Insp_Complete))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<Inw_Recpt_HeaderVM, Inw_Recpt_Header>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.Inw_Recpt_HeaderId))
          .ForMember(m => m.PoHeaderId, m => m.MapFrom(src => src.PoHeaderId))
          .ForMember(m => m.Supplier_Dc_Ref, m => m.MapFrom(src => src.Supplier_Dc_Ref))
          .ForMember(m => m.Supplier_Dc_Date, m => m.MapFrom(src => src.Supplier_Dc_Date))
          .ForMember(m => m.Supplier_Inv_ref, m => m.MapFrom(src => src.Supplier_Inv_ref))
          .ForMember(m => m.Supplier_Inv_date, m => m.MapFrom(src => src.Supplier_Inv_date))
          .ForMember(m => m.Inw_Date_time, m => m.MapFrom(src => src.Inw_Date_time))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<Inw_Recpt_Header, Inw_Recpt_HeaderVM>()
          .ForMember(m => m.Inw_Recpt_HeaderId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.PoHeaderId, m => m.MapFrom(src => src.PoHeaderId))
          .ForMember(m => m.Supplier_Dc_Ref, m => m.MapFrom(src => src.Supplier_Dc_Ref))
          .ForMember(m => m.Supplier_Dc_Date, m => m.MapFrom(src => src.Supplier_Dc_Date))
          .ForMember(m => m.Supplier_Inv_ref, m => m.MapFrom(src => src.Supplier_Inv_ref))
          .ForMember(m => m.Supplier_Inv_date, m => m.MapFrom(src => src.Supplier_Inv_date))
          .ForMember(m => m.Inw_Date_time, m => m.MapFrom(src => src.Inw_Date_time))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<Inw_Recpt_DetailsVM, Inw_Recpt_Details>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.Inw_Recpt_DetailsId))
          .ForMember(m => m.Inw_Recpt_Part_No_Id, m => m.MapFrom(src => src.Inw_Recpt_Part_No_Id))
          .ForMember(m => m.Inw_Recpt_Header_Id, m => m.MapFrom(src => src.Inw_Recpt_Header_Id))
          .ForMember(m => m.Our_count, m => m.MapFrom(src => src.Our_count))
          .ForMember(m => m.Vendor_DC_count, m => m.MapFrom(src => src.Vendor_DC_count))
          .ForMember(m => m.Inward_Condition, m => m.MapFrom(src => src.Inward_Condition))
          .ForMember(m => m.Comment, m => m.MapFrom(src => src.Comment))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<Inw_Recpt_Details, Inw_Recpt_DetailsVM>()
          .ForMember(m => m.Inw_Recpt_DetailsId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.Inw_Recpt_Part_No_Id, m => m.MapFrom(src => src.Inw_Recpt_Part_No_Id))
          .ForMember(m => m.Inw_Recpt_Header_Id, m => m.MapFrom(src => src.Inw_Recpt_Header_Id))
          .ForMember(m => m.Our_count, m => m.MapFrom(src => src.Our_count))
          .ForMember(m => m.Vendor_DC_count, m => m.MapFrom(src => src.Vendor_DC_count))
          .ForMember(m => m.Inward_Condition, m => m.MapFrom(src => src.Inward_Condition))
          .ForMember(m => m.Comment, m => m.MapFrom(src => src.Comment))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<Inv_Trans_LogVM, Inv_Trans_Log>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.Inv_Trans_LogId))
          .ForMember(m => m.Dt_time, m => m.MapFrom(src => src.Dt_time))
          .ForMember(m => m.PersonId, m => m.MapFrom(src => src.PersonId))
          .ForMember(m => m.Input_Part_NoId, m => m.MapFrom(src => src.Input_Part_NoId))
          .ForMember(m => m.Input_Routing_Id, m => m.MapFrom(src => src.Input_Routing_Id))
          .ForMember(m => m.Input_Opr_No, m => m.MapFrom(src => src.Input_Opr_No))
          .ForMember(m => m.Output_Part_No, m => m.MapFrom(src => src.Output_Part_No))
          .ForMember(m => m.Output_Routing_Id, m => m.MapFrom(src => src.Output_Routing_Id))
          .ForMember(m => m.Output_Opr_No, m => m.MapFrom(src => src.Output_Opr_No))
          .ForMember(m => m.Wo_Id, m => m.MapFrom(src => src.Wo_Id))
          .ForMember(m => m.PO_No_Id, m => m.MapFrom(src => src.PO_No_Id))
          .ForMember(m => m.Transaction_Id, m => m.MapFrom(src => src.Transaction_Id))
          .ForMember(m => m.Qnty, m => m.MapFrom(src => src.Qnty))
          .ForMember(m => m.From_Location_Id, m => m.MapFrom(src => src.From_Location_Id))
          .ForMember(m => m.To_Location_Id, m => m.MapFrom(src => src.To_Location_Id))
          .ForMember(m => m.Part_Status, m => m.MapFrom(src => src.Part_Status))
          .ForMember(m => m.Qnty_Mismatch, m => m.MapFrom(src => src.Qnty_Mismatch))
          .ForMember(m => m.Movement_Compl, m => m.MapFrom(src => src.Movement_Compl))
          .ForMember(m => m.Qnty_mismatch_status, m => m.MapFrom(src => src.Qnty_mismatch_status))
          .ForMember(m => m.Qnty_Mismatch_Comment, m => m.MapFrom(src => src.Qnty_Mismatch_Comment))
          .ForMember(m => m.Qnty_Mismatch_Resolution, m => m.MapFrom(src => src.Qnty_Mismatch_Resolution))
          .ForMember(m => m.Our_DC_Ref, m => m.MapFrom(src => src.Our_DC_Ref))
          .ForMember(m => m.Our_RGP_Ref, m => m.MapFrom(src => src.Our_RGP_Ref))
          .ForMember(m => m.NC_Log_Id, m => m.MapFrom(src => src.NC_Log_Id))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<Inv_Trans_Log, Inv_Trans_LogVM>()
          .ForMember(m => m.Inv_Trans_LogId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.Dt_time, m => m.MapFrom(src => src.Dt_time))
          .ForMember(m => m.PersonId, m => m.MapFrom(src => src.PersonId))
          .ForMember(m => m.Input_Part_NoId, m => m.MapFrom(src => src.Input_Part_NoId))
          .ForMember(m => m.Input_Routing_Id, m => m.MapFrom(src => src.Input_Routing_Id))
          .ForMember(m => m.Input_Opr_No, m => m.MapFrom(src => src.Input_Opr_No))
          .ForMember(m => m.Output_Part_No, m => m.MapFrom(src => src.Output_Part_No))
          .ForMember(m => m.Output_Routing_Id, m => m.MapFrom(src => src.Output_Routing_Id))
          .ForMember(m => m.Output_Opr_No, m => m.MapFrom(src => src.Output_Opr_No))
          .ForMember(m => m.Wo_Id, m => m.MapFrom(src => src.Wo_Id))
          .ForMember(m => m.PO_No_Id, m => m.MapFrom(src => src.PO_No_Id))
          .ForMember(m => m.Transaction_Id, m => m.MapFrom(src => src.Transaction_Id))
          .ForMember(m => m.Qnty, m => m.MapFrom(src => src.Qnty))
          .ForMember(m => m.From_Location_Id, m => m.MapFrom(src => src.From_Location_Id))
          .ForMember(m => m.To_Location_Id, m => m.MapFrom(src => src.To_Location_Id))
          .ForMember(m => m.Part_Status, m => m.MapFrom(src => src.Part_Status))
          .ForMember(m => m.Qnty_Mismatch, m => m.MapFrom(src => src.Qnty_Mismatch))
          .ForMember(m => m.Movement_Compl, m => m.MapFrom(src => src.Movement_Compl))
          .ForMember(m => m.Qnty_mismatch_status, m => m.MapFrom(src => src.Qnty_mismatch_status))
          .ForMember(m => m.Qnty_Mismatch_Comment, m => m.MapFrom(src => src.Qnty_Mismatch_Comment))
          .ForMember(m => m.Qnty_Mismatch_Resolution, m => m.MapFrom(src => src.Qnty_Mismatch_Resolution))
          .ForMember(m => m.Our_DC_Ref, m => m.MapFrom(src => src.Our_DC_Ref))
          .ForMember(m => m.Our_RGP_Ref, m => m.MapFrom(src => src.Our_RGP_Ref))
          .ForMember(m => m.NC_Log_Id, m => m.MapFrom(src => src.NC_Log_Id))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<Inventory_MasterVM, Inventory_Master>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.Inventory_MasterId))
          .ForMember(m => m.Dt_time, m => m.MapFrom(src => src.Dt_time))
          .ForMember(m => m.Part_NoId, m => m.MapFrom(src => src.Part_NoId))
          .ForMember(m => m.Routing_Id, m => m.MapFrom(src => src.Routing_Id))
          .ForMember(m => m.Opr_No_Id, m => m.MapFrom(src => src.Opr_No_Id))
          .ForMember(m => m.Current_QntOnHand, m => m.MapFrom(src => src.Current_QntOnHand))
          .ForMember(m => m.Location_Id, m => m.MapFrom(src => src.Location_Id))
          .ForMember(m => m.Inv_Trans_Log_Id, m => m.MapFrom(src => src.Inv_Trans_Log_Id))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<Inventory_Master, Inventory_MasterVM>()
          .ForMember(m => m.Inventory_MasterId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.Dt_time, m => m.MapFrom(src => src.Dt_time))
          .ForMember(m => m.Part_NoId, m => m.MapFrom(src => src.Part_NoId))
          .ForMember(m => m.Routing_Id, m => m.MapFrom(src => src.Routing_Id))
          .ForMember(m => m.Opr_No_Id, m => m.MapFrom(src => src.Opr_No_Id))
          .ForMember(m => m.Current_QntOnHand, m => m.MapFrom(src => src.Current_QntOnHand))
          .ForMember(m => m.Location_Id, m => m.MapFrom(src => src.Location_Id))
          .ForMember(m => m.Inv_Trans_Log_Id, m => m.MapFrom(src => src.Inv_Trans_Log_Id))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<Part_StatusVM, Part_Status>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.Part_Status_Id))
          .ForMember(m => m.Part_Status_desc, m => m.MapFrom(src => src.Part_Status_desc));
            CreateMap<Part_Status, Part_StatusVM>()
          .ForMember(m => m.Part_Status_Id, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.Part_Status_desc, m => m.MapFrom(src => src.Part_Status_desc));
            CreateMap<NC_Disp_Decision_ListVM, NC_Disp_Decision_List>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.NC_Disp_Decision_ListId))
          .ForMember(m => m.NC_Disp_Decision_Desc, m => m.MapFrom(src => src.NC_Disp_Decision_Desc));
            CreateMap<NC_Disp_Decision_List, NC_Disp_Decision_ListVM>()
          .ForMember(m => m.NC_Disp_Decision_ListId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.NC_Disp_Decision_Desc, m => m.MapFrom(src => src.NC_Disp_Decision_Desc));
            CreateMap<NC_work_StatusVM, NC_work_Status>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.NC_work_StatusId))
          .ForMember(m => m.NC_work_Status_Desc, m => m.MapFrom(src => src.NC_work_Status_Desc));
            CreateMap<NC_work_Status, NC_work_StatusVM>()
          .ForMember(m => m.NC_work_StatusId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.NC_work_Status_Desc, m => m.MapFrom(src => src.NC_work_Status_Desc));
            CreateMap<Cont_RCA_CA_Status_ListVM, Cont_RCA_CA_Status_List>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.Cont_RCA_CA_Status_ListId))
          .ForMember(m => m.Status_Desc, m => m.MapFrom(src => src.Status_Desc));
            CreateMap<Cont_RCA_CA_Status_List, Cont_RCA_CA_Status_ListVM>()
          .ForMember(m => m.Cont_RCA_CA_Status_ListId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.Status_Desc, m => m.MapFrom(src => src.Status_Desc));
            CreateMap<NC_Wk_List_Tmpl_HeadVM, NC_Wk_List_Tmpl_Head>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.NC_Wk_List_Tmpl_HeadId))
          .ForMember(m => m.NC_Disp_Decision_Id, m => m.MapFrom(src => src.NC_Disp_Decision_Id))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId))
          .ForMember(m => m.No_of_steps, m => m.MapFrom(src => src.No_of_steps));
            CreateMap<NC_Wk_List_Tmpl_Head, NC_Wk_List_Tmpl_HeadVM>()
          .ForMember(m => m.NC_Wk_List_Tmpl_HeadId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.NC_Disp_Decision_Id, m => m.MapFrom(src => src.NC_Disp_Decision_Id))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId))
          .ForMember(m => m.No_of_steps, m => m.MapFrom(src => src.No_of_steps));
            CreateMap<NC_Disp_Decs_Appl_ListVM, NC_Disp_Decs_Appl_List>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.NC_Disp_Decs_Appl_ListId))
          .ForMember(m => m.NC_Disp_Decision_Id, m => m.MapFrom(src => src.NC_Disp_Decision_Id))
          .ForMember(m => m.Bof, m => m.MapFrom(src => src.Bof))
          .ForMember(m => m.Cmp, m => m.MapFrom(src => src.Cmp))
          .ForMember(m => m.Assy, m => m.MapFrom(src => src.Assy))
          .ForMember(m => m.Rm, m => m.MapFrom(src => src.Rm))
          .ForMember(m => m.Level_2_Dec_Reqd, m => m.MapFrom(src => src.Level_2_Dec_Reqd))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<NC_Disp_Decs_Appl_List, NC_Disp_Decs_Appl_ListVM>()
          .ForMember(m => m.NC_Disp_Decs_Appl_ListId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.NC_Disp_Decision_Id, m => m.MapFrom(src => src.NC_Disp_Decision_Id))
          .ForMember(m => m.Bof, m => m.MapFrom(src => src.Bof))
          .ForMember(m => m.Cmp, m => m.MapFrom(src => src.Cmp))
          .ForMember(m => m.Assy, m => m.MapFrom(src => src.Assy))
          .ForMember(m => m.Rm, m => m.MapFrom(src => src.Rm))
          .ForMember(m => m.Level_2_Dec_Reqd, m => m.MapFrom(src => src.Level_2_Dec_Reqd))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<NC_Wk_List_Tmpl_DetVM, NC_Wk_List_Tmpl_Det>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.NC_Wk_List_Tmpl_DetId))
          .ForMember(m => m.NC_Wk_List_Tmpl_Appl_Id, m => m.MapFrom(src => src.NC_Wk_List_Tmpl_Appl_Id))
          .ForMember(m => m.NC_Wk_Step_Desc, m => m.MapFrom(src => src.NC_Wk_Step_Desc))
          .ForMember(m => m.Resp_Dept, m => m.MapFrom(src => src.Resp_Dept))
          .ForMember(m => m.UI_ID, m => m.MapFrom(src => src.UI_ID))
          .ForMember(m => m.Seq_no, m => m.MapFrom(src => src.Seq_no))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<NC_Wk_List_Tmpl_Det, NC_Wk_List_Tmpl_DetVM>()
          .ForMember(m => m.NC_Wk_List_Tmpl_DetId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.NC_Wk_List_Tmpl_Appl_Id, m => m.MapFrom(src => src.NC_Wk_List_Tmpl_Appl_Id))
          .ForMember(m => m.NC_Wk_Step_Desc, m => m.MapFrom(src => src.NC_Wk_Step_Desc))
          .ForMember(m => m.Resp_Dept, m => m.MapFrom(src => src.Resp_Dept))
          .ForMember(m => m.UI_ID, m => m.MapFrom(src => src.UI_ID))
          .ForMember(m => m.Seq_no, m => m.MapFrom(src => src.Seq_no))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<NC_Disp_Dec_MakerVM, NC_Disp_Dec_Maker>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.NC_Disp_Dec_MakerId))
          .ForMember(m => m.Level_2_dec_maker, m => m.MapFrom(src => src.Level_2_dec_maker))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId))
          .ForMember(m => m.Level_1_dec_maker, m => m.MapFrom(src => src.Level_1_dec_maker));
            CreateMap<NC_Disp_Dec_Maker, NC_Disp_Dec_MakerVM>()
          .ForMember(m => m.NC_Disp_Dec_MakerId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.Level_2_dec_maker, m => m.MapFrom(src => src.Level_2_dec_maker))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId))
          .ForMember(m => m.Level_1_dec_maker, m => m.MapFrom(src => src.Level_1_dec_maker));
            CreateMap<Qnty_Mismatch_listVM, Qnty_Mismatch_list>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.Qnty_Mismatch_listId))
          .ForMember(m => m.Qnty_Mismatch_Desc, m => m.MapFrom(src => src.Qnty_Mismatch_Desc));
            CreateMap<Qnty_Mismatch_list, Qnty_Mismatch_listVM>()
          .ForMember(m => m.Qnty_Mismatch_listId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.Qnty_Mismatch_Desc, m => m.MapFrom(src => src.Qnty_Mismatch_Desc));
            CreateMap<Insp_Outcome_ListVM, Insp_Outcome_List>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.Insp_Outcome_ListId))
          .ForMember(m => m.Insp_Outcome_desc, m => m.MapFrom(src => src.Insp_Outcome_desc))
          .ForMember(m => m.Applicability, m => m.MapFrom(src => src.Applicability))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<Insp_Outcome_List, Insp_Outcome_ListVM>()
          .ForMember(m => m.Insp_Outcome_ListId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.Insp_Outcome_desc, m => m.MapFrom(src => src.Insp_Outcome_desc))
          .ForMember(m => m.Applicability, m => m.MapFrom(src => src.Applicability))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<NC_Work_ListVM, NC_Work_List>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.NC_Work_ListId))
          .ForMember(m => m.NC_Work_List_Header_Id, m => m.MapFrom(src => src.NC_Work_List_Header_Id))
          .ForMember(m => m.Step_Desc, m => m.MapFrom(src => src.Step_Desc))
          .ForMember(m => m.Resp_Dept, m => m.MapFrom(src => src.Resp_Dept))
          .ForMember(m => m.Seq_No, m => m.MapFrom(src => src.Seq_No))
          .ForMember(m => m.NC_Work_status_Id, m => m.MapFrom(src => src.NC_Work_status_Id))
          .ForMember(m => m.Start_Date, m => m.MapFrom(src => src.Start_Date))
          .ForMember(m => m.End_Date, m => m.MapFrom(src => src.End_Date))
          .ForMember(m => m.Resp_Person, m => m.MapFrom(src => src.Resp_Person))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<Insp_Outcome_List, Insp_Outcome_ListVM>()
          .ForMember(m => m.Insp_Outcome_ListId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.Insp_Outcome_desc, m => m.MapFrom(src => src.Insp_Outcome_desc))
          .ForMember(m => m.Applicability, m => m.MapFrom(src => src.Applicability))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<Cont_RCA_CA_LogVM, Cont_RCA_CA_Log>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.Cont_RCA_CA_LogId))
          .ForMember(m => m.NcLogId, m => m.MapFrom(src => src.NcLogId))
          .ForMember(m => m.Containment_Action, m => m.MapFrom(src => src.Containment_Action))
          .ForMember(m => m.Senior_Feedback, m => m.MapFrom(src => src.Senior_Feedback))
          .ForMember(m => m.Cont_RCA_CA_Status_Id, m => m.MapFrom(src => src.Cont_RCA_CA_Status_Id))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<Cont_RCA_CA_Log, Cont_RCA_CA_LogVM>()
          .ForMember(m => m.Cont_RCA_CA_LogId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.NcLogId, m => m.MapFrom(src => src.NcLogId))
          .ForMember(m => m.Containment_Action, m => m.MapFrom(src => src.Containment_Action))
          .ForMember(m => m.Senior_Feedback, m => m.MapFrom(src => src.Senior_Feedback))
          .ForMember(m => m.Cont_RCA_CA_Status_Id, m => m.MapFrom(src => src.Cont_RCA_CA_Status_Id))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<NC_Decision_LogVM, NC_Decision_Log>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.NC_Decision_LogId))
          .ForMember(m => m.NcLogId, m => m.MapFrom(src => src.NcLogId))
          .ForMember(m => m.RedoCA, m => m.MapFrom(src => src.RedoCA))
          .ForMember(m => m.Cust_Decision_Reqd, m => m.MapFrom(src => src.Cust_Decision_Reqd))
          .ForMember(m => m.Cust_Dec_Request, m => m.MapFrom(src => src.Cust_Dec_Request))
          .ForMember(m => m.Cust_Request_date, m => m.MapFrom(src => src.Cust_Request_date))
          .ForMember(m => m.Cust_feedback_date, m => m.MapFrom(src => src.Cust_feedback_date))
          .ForMember(m => m.Cust_feedback_Id, m => m.MapFrom(src => src.Cust_feedback_Id))
          .ForMember(m => m.Cust_Feedback_Desc, m => m.MapFrom(src => src.Cust_Feedback_Desc))
          .ForMember(m => m.NC_Disp_Decision_Id, m => m.MapFrom(src => src.NC_Disp_Decision_Id))
          .ForMember(m => m.NC_Disp_Instruction, m => m.MapFrom(src => src.NC_Disp_Instruction))
          .ForMember(m => m.NC_Disp_Deci_Lvl1_Id, m => m.MapFrom(src => src.NC_Disp_Deci_Lvl1_Id))
          .ForMember(m => m.NC_Disp_Deci_Lvl2_Id, m => m.MapFrom(src => src.NC_Disp_Deci_Lvl2_Id))
          .ForMember(m => m.NC_Disp_Inst_Lvl1, m => m.MapFrom(src => src.NC_Disp_Inst_Lvl1))
          .ForMember(m => m.NC_Disp_Inst_Lvl2, m => m.MapFrom(src => src.NC_Disp_Inst_Lvl2))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<NC_Decision_Log, NC_Decision_LogVM>()
          .ForMember(m => m.NC_Decision_LogId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.NcLogId, m => m.MapFrom(src => src.NcLogId))
          .ForMember(m => m.RedoCA, m => m.MapFrom(src => src.RedoCA))
          .ForMember(m => m.Cust_Decision_Reqd, m => m.MapFrom(src => src.Cust_Decision_Reqd))
          .ForMember(m => m.Cust_Dec_Request, m => m.MapFrom(src => src.Cust_Dec_Request))
          .ForMember(m => m.Cust_Request_date, m => m.MapFrom(src => src.Cust_Request_date))
          .ForMember(m => m.Cust_feedback_date, m => m.MapFrom(src => src.Cust_feedback_date))
          .ForMember(m => m.Cust_feedback_Id, m => m.MapFrom(src => src.Cust_feedback_Id))
          .ForMember(m => m.Cust_Feedback_Desc, m => m.MapFrom(src => src.Cust_Feedback_Desc))
          .ForMember(m => m.NC_Disp_Deci_Lvl1_Id, m => m.MapFrom(src => src.NC_Disp_Deci_Lvl1_Id))
          .ForMember(m => m.NC_Disp_Deci_Lvl2_Id, m => m.MapFrom(src => src.NC_Disp_Deci_Lvl2_Id))
          .ForMember(m => m.NC_Disp_Inst_Lvl1, m => m.MapFrom(src => src.NC_Disp_Inst_Lvl1))
          .ForMember(m => m.NC_Disp_Inst_Lvl2, m => m.MapFrom(src => src.NC_Disp_Inst_Lvl2))
          .ForMember(m => m.NC_Disp_Decision_Id, m => m.MapFrom(src => src.NC_Disp_Decision_Id))
          .ForMember(m => m.NC_Disp_Instruction, m => m.MapFrom(src => src.NC_Disp_Instruction))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<Insp_Outcome_DetailsVM, Insp_Outcome_Details>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.Insp_Outcome_Details_Id))
          .ForMember(m => m.Inw_Recpt_Header_Id, m => m.MapFrom(src => src.Inw_Recpt_Header_Id))
          .ForMember(m => m.Inw_Insp_Log_Id, m => m.MapFrom(src => src.Inw_Insp_Log_Id))
          .ForMember(m => m.Inw_Recpt_Part_No_Id, m => m.MapFrom(src => src.Inw_Recpt_Part_No_Id))
          .ForMember(m => m.Shop_Insp_log_Id, m => m.MapFrom(src => src.Shop_Insp_log_Id))
          .ForMember(m => m.Final_Insp_log_Id, m => m.MapFrom(src => src.Final_Insp_log_Id))
          .ForMember(m => m.NC_Tracking_No, m => m.MapFrom(src => src.NC_Tracking_No))
          .ForMember(m => m.Balloon_No_Dir, m => m.MapFrom(src => src.Balloon_No_Dir))
          .ForMember(m => m.Balloon_No, m => m.MapFrom(src => src.Balloon_No))
          .ForMember(m => m.Feature_Descrip, m => m.MapFrom(src => src.Feature_Descrip))
          .ForMember(m => m.NC_Descrip, m => m.MapFrom(src => src.NC_Descrip))
          .ForMember(m => m.NC_Qnty, m => m.MapFrom(src => src.NC_Qnty))
          .ForMember(m => m.Decl_by_Supplier, m => m.MapFrom(src => src.Decl_by_Supplier))
          .ForMember(m => m.Storage_Location, m => m.MapFrom(src => src.Storage_Location))
          .ForMember(m => m.Label_Type, m => m.MapFrom(src => src.Label_Type))
          .ForMember(m => m.NC_Log_status_Id, m => m.MapFrom(src => src.NC_Log_status_Id))
          .ForMember(m => m.CreationDate, m => m.MapFrom(src => src.NcDate))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<Insp_Outcome_Details, Insp_Outcome_DetailsVM>()
          .ForMember(m => m.Insp_Outcome_Details_Id, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.Inw_Insp_Log_Id, m => m.MapFrom(src => src.Inw_Insp_Log_Id))
          .ForMember(m => m.Inw_Recpt_Header_Id, m => m.MapFrom(src => src.Inw_Recpt_Header_Id))
          .ForMember(m => m.Inw_Recpt_Part_No_Id, m => m.MapFrom(src => src.Inw_Recpt_Part_No_Id))
          .ForMember(m => m.Shop_Insp_log_Id, m => m.MapFrom(src => src.Shop_Insp_log_Id))
          .ForMember(m => m.Final_Insp_log_Id, m => m.MapFrom(src => src.Final_Insp_log_Id))
          .ForMember(m => m.NC_Tracking_No, m => m.MapFrom(src => src.NC_Tracking_No))
          .ForMember(m => m.Balloon_No_Dir, m => m.MapFrom(src => src.Balloon_No_Dir))
          .ForMember(m => m.Balloon_No, m => m.MapFrom(src => src.Balloon_No))
          .ForMember(m => m.Feature_Descrip, m => m.MapFrom(src => src.Feature_Descrip))
          .ForMember(m => m.NC_Descrip, m => m.MapFrom(src => src.NC_Descrip))
          .ForMember(m => m.NC_Qnty, m => m.MapFrom(src => src.NC_Qnty))
          .ForMember(m => m.Decl_by_Supplier, m => m.MapFrom(src => src.Decl_by_Supplier))
          .ForMember(m => m.Storage_Location, m => m.MapFrom(src => src.Storage_Location))
          .ForMember(m => m.Label_Type, m => m.MapFrom(src => src.Label_Type))
          .ForMember(m => m.NC_Log_status_Id, m => m.MapFrom(src => src.NC_Log_status_Id))
          .ForMember(m => m.NcDate, m => m.MapFrom(src => src.CreationDate))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<Inward_Condn_listVM, Inward_Condn_list>()
          .ForMember(m => m.Id, m => m.MapFrom(src => src.Inward_Condn_listId))
          .ForMember(m => m.Inward_Condn_desc, m => m.MapFrom(src => src.Inward_Condn_desc))
          .ForMember(m => m.Applicability, m => m.MapFrom(src => src.Applicability))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));
            CreateMap<Inward_Condn_list, Inward_Condn_listVM>()
          .ForMember(m => m.Inward_Condn_listId, m => m.MapFrom(src => src.Id))
          .ForMember(m => m.Inward_Condn_desc, m => m.MapFrom(src => src.Inward_Condn_desc))
          .ForMember(m => m.Applicability, m => m.MapFrom(src => src.Applicability))
          .ForMember(m => m.TenantId, m => m.MapFrom(src => src.TenantId));

            CreateMap<InwardDocType, InwardDocTypeVM>()
            .ForMember(s => s.InwardDocTypeId, s => s.MapFrom(src => src.Id))
            .ForMember(s => s.DocumentTypeId, s => s.MapFrom(src => src.DocumentTypeId))
            .ForMember(s => s.Mandatory, s => s.MapFrom(src => src.Mandatory))
            .ForMember(s => s.UpdatedBy, s => s.MapFrom(src => src.UpdatedBy))
            .ForMember(s => s.UpdatedOn, s => s.MapFrom(src => src.UpdatedOn));

            CreateMap<InwardDocTypeVM, InwardDocType>()
            .ForMember(s => s.Id, s => s.MapFrom(src => src.InwardDocTypeId))
            .ForMember(s => s.DocumentTypeId, s => s.MapFrom(src => src.DocumentTypeId))
            .ForMember(s => s.Mandatory, s => s.MapFrom(src => src.Mandatory))
            .ForMember(s => s.UpdatedBy, s => s.MapFrom(src => src.UpdatedBy))
            .ForMember(s => s.UpdatedOn, s => s.MapFrom(src => src.UpdatedOn));

            CreateMap<RcCaDocType, RcCaDocTypeVM>()
            .ForMember(s => s.RcCaDocTypeId, s => s.MapFrom(src => src.Id))
            .ForMember(s => s.DocumentTypeId, s => s.MapFrom(src => src.DocumentTypeId))
            .ForMember(s => s.Mandatory, s => s.MapFrom(src => src.Mandatory))
            .ForMember(s => s.UpdatedBy, s => s.MapFrom(src => src.UpdatedBy))
            .ForMember(s => s.UpdatedOn, s => s.MapFrom(src => src.UpdatedOn));

            CreateMap<RcCaDocTypeVM, RcCaDocType>()
            .ForMember(s => s.Id, s => s.MapFrom(src => src.RcCaDocTypeId))
            .ForMember(s => s.DocumentTypeId, s => s.MapFrom(src => src.DocumentTypeId))
            .ForMember(s => s.Mandatory, s => s.MapFrom(src => src.Mandatory))
            .ForMember(s => s.UpdatedBy, s => s.MapFrom(src => src.UpdatedBy))
            .ForMember(s => s.UpdatedOn, s => s.MapFrom(src => src.UpdatedOn));
            CreateMap<LineInspectDocType, LineInspectDocTypeVM>()
            .ForMember(s => s.LineInspectDocTypeId, s => s.MapFrom(src => src.Id))
            .ForMember(s => s.DocumentTypeId, s => s.MapFrom(src => src.DocumentTypeId))
            .ForMember(s => s.Mandatory, s => s.MapFrom(src => src.Mandatory))
            .ForMember(s => s.UpdatedBy, s => s.MapFrom(src => src.UpdatedBy))
            .ForMember(s => s.UpdatedOn, s => s.MapFrom(src => src.UpdatedOn));

            CreateMap<LineInspectDocTypeVM, LineInspectDocType>()
            .ForMember(s => s.Id, s => s.MapFrom(src => src.LineInspectDocTypeId))
            .ForMember(s => s.DocumentTypeId, s => s.MapFrom(src => src.DocumentTypeId))
            .ForMember(s => s.Mandatory, s => s.MapFrom(src => src.Mandatory))
            .ForMember(s => s.UpdatedBy, s => s.MapFrom(src => src.UpdatedBy))
            .ForMember(s => s.UpdatedOn, s => s.MapFrom(src => src.UpdatedOn));
            CreateMap<FinalInspectDocType, FinalInspectDocTypeVM>()
            .ForMember(s => s.FinalInspectDocTypeId, s => s.MapFrom(src => src.Id))
            .ForMember(s => s.DocumentTypeId, s => s.MapFrom(src => src.DocumentTypeId))
            .ForMember(s => s.Mandatory, s => s.MapFrom(src => src.Mandatory))
            .ForMember(s => s.UpdatedBy, s => s.MapFrom(src => src.UpdatedBy))
            .ForMember(s => s.UpdatedOn, s => s.MapFrom(src => src.UpdatedOn));

            CreateMap<FinalInspectDocTypeVM, FinalInspectDocType>()
            .ForMember(s => s.Id, s => s.MapFrom(src => src.FinalInspectDocTypeId))
            .ForMember(s => s.DocumentTypeId, s => s.MapFrom(src => src.DocumentTypeId))
            .ForMember(s => s.Mandatory, s => s.MapFrom(src => src.Mandatory))
            .ForMember(s => s.UpdatedBy, s => s.MapFrom(src => src.UpdatedBy))
            .ForMember(s => s.UpdatedOn, s => s.MapFrom(src => src.UpdatedOn));
            CreateMap<InspectDocType, InspectDocTypeVM>()
            .ForMember(s => s.InspectDocTypeId, s => s.MapFrom(src => src.Id))
            .ForMember(s => s.DocumentTypeId, s => s.MapFrom(src => src.DocumentTypeId))
            .ForMember(s => s.Mandatory, s => s.MapFrom(src => src.Mandatory))
            .ForMember(s => s.UpdatedBy, s => s.MapFrom(src => src.UpdatedBy))
            .ForMember(s => s.UpdatedOn, s => s.MapFrom(src => src.UpdatedOn));

            CreateMap<InspectDocTypeVM, InspectDocType>()
            .ForMember(s => s.Id, s => s.MapFrom(src => src.InspectDocTypeId))
            .ForMember(s => s.DocumentTypeId, s => s.MapFrom(src => src.DocumentTypeId))
            .ForMember(s => s.Mandatory, s => s.MapFrom(src => src.Mandatory))
            .ForMember(s => s.UpdatedBy, s => s.MapFrom(src => src.UpdatedBy))
            .ForMember(s => s.UpdatedOn, s => s.MapFrom(src => src.UpdatedOn));

            CreateMap<NcLogStatus, NcLogStatusVM>()
            .ForMember(s => s.NC_Log_Status_List_Id, s => s.MapFrom(src => src.Id))
            .ForMember(s => s.Nc_Log_Status_Desc, s => s.MapFrom(src => src.Nc_Log_Status_Desc));

            CreateMap<NcLogStatusVM, NcLogStatus>()
            .ForMember(s => s.Id, s => s.MapFrom(src => src.NC_Log_Status_List_Id))
            .ForMember(s => s.Nc_Log_Status_Desc, s => s.MapFrom(src => src.Nc_Log_Status_Desc));
            CreateMap<OperationSettings, OperationSettingsVM>()
            .ForMember(s => s.OperationSettingsId, s => s.MapFrom(src => src.Id))
            .ForMember(s => s.EnableDisable, s => s.MapFrom(src => src.EnableDisable))
            .ForMember(s => s.TenantId, s => s.MapFrom(src => src.TenantId))
            .ForMember(s => s.UiName, s => s.MapFrom(src => src.UiName));

            CreateMap<OperationSettingsVM, OperationSettings>()
            .ForMember(s => s.Id, s => s.MapFrom(src => src.OperationSettingsId))
            .ForMember(s => s.EnableDisable, s => s.MapFrom(src => src.EnableDisable))
            .ForMember(s => s.TenantId, s => s.MapFrom(src => src.TenantId))
            .ForMember(s => s.UiName, s => s.MapFrom(src => src.UiName));
        }
    }
}
